import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import Navbar from '../../../components/feature/Navbar';
import Footer from '../../../components/feature/Footer';
import { PageHeader, inputClasses } from '../../../components/ui';
import { communityProgramsApi, type AnnualReport, type CommunityBusiness } from '../../../lib/api/community-programs';

export default function CommunityResourcesPage() {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en');
  const metricLabel = (key: string) => ({
    newMembers: fr ? 'Nouveaux membres' : 'New members',
    eventRegistrations: fr ? 'Inscriptions' : 'Registrations',
    volunteerHours: fr ? 'Heures bénévoles' : 'Volunteer hours',
    serviceRequests: fr ? 'Demandes de service' : 'Service requests',
    appointments: fr ? 'Rendez-vous' : 'Appointments',
    businessesPublished: fr ? 'Entreprises publiées' : 'Published businesses',
    grantApplications: fr ? 'Demandes de bourse' : 'Grant applications',
  }[key] || key);
  const [items, setItems] = useState<CommunityBusiness[]>([]); const [reports, setReports] = useState<AnnualReport[]>([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [province, setProvince] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); Promise.all([communityProgramsApi.directory(search, category, province), communityProgramsApi.reports()]).then(([directory, annual]) => { setItems(directory.data || []); setReports(annual.data || []); }).finally(() => setLoading(false)); }, 180); return () => window.clearTimeout(timer); }, [search, category, province]);
  const categories = useMemo(() => [...new Set(items.map((item) => item.category))].sort(), [items]);
  return <div className="min-h-screen bg-background"><Navbar /><main><PageHeader variant="interior" eyebrow={fr ? 'Acheter, trouver, collaborer' : 'Buy, find, collaborate'} title={fr ? 'Le répertoire qui fait circuler la confiance.' : 'A directory built around community trust.'} description={fr ? 'Découvrez des entreprises et ressources proposées par les membres, puis vérifiées par le HCBE Canada.' : 'Discover member-owned businesses and resources reviewed by HCBE Canada.'} />
    <section className="mx-auto w-full max-w-[1440px] px-margin-mobile py-12 md:px-margin-desktop lg:py-16"><div className="grid gap-3 rounded-[24px] border border-line bg-surface p-4 shadow-[0_16px_45px_rgba(0,59,27,.06)] md:grid-cols-[1fr_240px_240px]"><label><span className="sr-only">{fr ? 'Rechercher' : 'Search'}</span><span className="relative block"><i className="ri-search-line absolute left-4 top-1/2 -translate-y-1/2 text-green" /><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${inputClasses} pl-11`} placeholder={fr ? 'Nom, service ou mot-clé…' : 'Name, service, or keyword…'} /></span></label><select aria-label={fr ? 'Catégorie' : 'Category'} value={category} onChange={(e) => setCategory(e.target.value)} className={inputClasses}><option value="">{fr ? 'Toutes les catégories' : 'All categories'}</option>{categories.map((value) => <option key={value}>{value}</option>)}</select><input aria-label={fr ? 'Province' : 'Province'} value={province} onChange={(e) => setProvince(e.target.value)} className={inputClasses} placeholder={fr ? 'Province ou territoire' : 'Province or territory'} /></div>
      <div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="group relative overflow-hidden rounded-[26px] border border-line bg-surface p-6 transition hover:-translate-y-1 hover:shadow-[0_20px_50px_rgba(0,59,27,.1)]"><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-gold/[.08]" />{item.isFeatured && <span className="relative inline-flex rounded-full bg-gold px-3 py-1 text-[8px] font-bold uppercase tracking-wider text-green-deep">{fr ? 'À découvrir' : 'Featured'}</span>}<div className="relative mt-5 flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-green text-xl font-bold text-white">{item.logoUrl ? <img src={item.logoUrl} alt="" className="h-full w-full object-cover" /> : item.name.slice(0, 2).toUpperCase()}</span><div><p className="text-[9px] font-bold uppercase tracking-wider text-red-link">{item.category}</p><h2 className="mt-1 font-display text-2xl font-bold text-green-deep">{fr ? item.name : item.nameEn || item.name}</h2><p className="mt-1 text-xs text-ink-variant">{[item.city, item.province].filter(Boolean).join(' · ')}</p></div></div><p className="relative mt-5 line-clamp-4 text-sm leading-6 text-ink-variant">{fr ? item.description : item.descriptionEn || item.description}</p><div className="relative mt-6 flex flex-wrap gap-2 border-t border-line pt-5">{item.websiteUrl && <a href={item.websiteUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-green px-4 text-[10px] font-bold uppercase tracking-wider text-white">{fr ? 'Visiter' : 'Visit'} <i className="ri-external-link-line" /></a>}<a href={`mailto:${item.contactEmail}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-green/20 px-4 text-[10px] font-bold uppercase tracking-wider text-green">{fr ? 'Contacter' : 'Contact'}</a></div></article>)}{!loading && items.length === 0 && <div className="rounded-[24px] border border-dashed border-line bg-surface p-10 text-center md:col-span-2 xl:col-span-3"><i className="ri-store-2-line text-4xl text-green" /><h2 className="mt-4 font-display text-2xl font-bold text-green-deep">{fr ? 'Aucune fiche ne correspond.' : 'No listing matches.'}</h2></div>}</div>
      {reports.length > 0 && <section className="mt-16 border-t border-line pt-12"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-link">{fr ? 'Transparence' : 'Transparency'}</p><h2 className="mt-2 font-display text-3xl font-bold text-green-deep">{fr ? 'Rapports annuels publiés' : 'Published annual reports'}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{reports.map((report) => <article key={report.id} className="rounded-[22px] bg-green-deep p-6 text-white"><p className="text-5xl font-bold text-gold">{report.year}</p><h3 className="mt-4 font-display text-xl font-bold">{fr ? report.title : report.titleEn || report.title}</h3><p className="mt-2 text-sm leading-6 text-green-dim">{fr ? report.summary : report.summaryEn || report.summary}</p><div className="mt-5 grid grid-cols-3 gap-2">{Object.entries(report.metrics).slice(0, 3).map(([key, value]) => <div key={key} className="rounded-xl border border-white/10 bg-white/[.05] p-3"><strong className="block text-xl text-gold">{value}</strong><span className="mt-1 block text-[8px] uppercase leading-3 text-green-dim">{metricLabel(key)}</span></div>)}</div></article>)}</div></section>}
    </section></main><Footer /></div>;
}
