import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { associationsApi } from '../../../../lib/api/associations';
import { membersApi } from '../../../../lib/api/members';
import type { AssociationMember, AssociationPermission, AssociationWorkspace, MemberDto } from '../../../../lib/api/types';
import { Button, EmptyState, Field, inputClasses } from '../../../../components/ui';

const permissionOptions: { value: AssociationPermission; fr: string; en: string }[] = [
  { value: 'workspace.view', fr: 'Accès au portail', en: 'Workspace access' },
  { value: 'profile.manage', fr: 'Profil public', en: 'Public profile' },
  { value: 'members.manage', fr: 'Membres', en: 'Members' },
  { value: 'documents.manage', fr: 'Documents', en: 'Documents' },
  { value: 'calendar.manage', fr: 'Calendrier', en: 'Calendar' },
  { value: 'service-cases.manage', fr: 'Demandes de services', en: 'Service requests' },
];

export function OrganizationWorkspaceAdmin({ associationId }: { associationId: string }) {
  const { i18n } = useTranslation(); const fr = i18n.language.startsWith('fr');
  const [workspace, setWorkspace] = useState<AssociationWorkspace | null>(null); const [members, setMembers] = useState<MemberDto[]>([]); const [error, setError] = useState('');
  const [candidateId, setCandidateId] = useState(''); const [role, setRole] = useState<AssociationMember['role']>('Member'); const [title, setTitle] = useState(''); const [selectedPermissions, setSelectedPermissions] = useState<AssociationPermission[]>(['workspace.view']);
  const load = async () => { try { const [workspaceResponse, memberResponse] = await Promise.all([associationsApi.getWorkspaceForAdmin(associationId), membersApi.getAllMembers()]); if (workspaceResponse.data) setWorkspace(workspaceResponse.data); else setError(workspaceResponse.message || 'Error'); setMembers(memberResponse.data ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Error'); } };
  useEffect(() => { void load(); }, [associationId]);
  const availableMembers = useMemo(() => members.filter((item) => !workspace?.members.some((member) => member.memberId === item.id)), [members, workspace]);
  const add = async (event: React.FormEvent) => { event.preventDefault(); if (!candidateId) return; const response = await associationsApi.upsertMemberForAdmin(associationId, { memberId: candidateId, role, title, permissions: selectedPermissions, status: 'Active' }); if (!response.success) setError(response.message || 'Error'); else { setCandidateId(''); setTitle(''); await load(); } };
  const review = async (requestId: string, status: 'Approved' | 'Rejected') => { const response = await associationsApi.reviewMembershipForAdmin(associationId, requestId, { status, role: 'Member', permissions: ['workspace.view'] }); if (!response.success) setError(response.message || 'Error'); else await load(); };
  const remove = async (member: AssociationMember) => { if (member.role === 'Owner' || !window.confirm(fr ? `Retirer ${member.memberName} ?` : `Remove ${member.memberName}?`)) return; const response = await associationsApi.removeMemberForAdmin(associationId, member.id); if (!response.success) setError(response.message || 'Error'); else await load(); };
  if (!workspace) return <section className="rounded-2xl border border-line bg-surface p-6">{error ? <p className="text-error">{error}</p> : <p className="text-center text-green"><i className="ri-loader-4-line animate-spin text-2xl" /></p>}</section>;
  const pending = workspace.joinRequests.filter((item) => item.status === 'Pending');
  return <section className="overflow-hidden rounded-[24px] border border-line bg-surface shadow-[0_12px_40px_rgba(0,59,27,.06)]">
    <header className="flex flex-col gap-3 border-b border-line bg-green-deep px-6 py-5 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-gold">{fr ? 'Espace privé' : 'Private workspace'}</p><h2 className="mt-1 font-display text-2xl font-bold text-white">{fr ? 'Accès et gouvernance' : 'Access and governance'}</h2></div><div className="flex gap-2"><span className="rounded-full border border-white/15 bg-white/[.07] px-3 py-1.5 text-[10px]">{workspace.members.length} {fr ? 'membres' : 'members'}</span><span className="rounded-full border border-white/15 bg-white/[.07] px-3 py-1.5 text-[10px]">{pending.length} {fr ? 'en attente' : 'pending'}</span></div></header>
    {error && <p className="m-5 rounded-xl border border-error/30 bg-error/5 p-3 text-sm text-error">{error}</p>}
    <div className="grid gap-8 p-6 xl:grid-cols-[1fr_360px]">
      <div className="space-y-8"><div><Heading title={fr ? 'Responsables et membres' : 'Leaders and members'} count={workspace.members.length} /><div className="mt-4 overflow-hidden rounded-2xl border border-line"><div className="hidden grid-cols-[1.2fr_.7fr_1fr_auto] gap-4 bg-canvas px-4 py-3 text-[9px] font-bold uppercase tracking-[.12em] text-ink-variant md:grid"><span>{fr ? 'Membre' : 'Member'}</span><span>{fr ? 'Rôle' : 'Role'}</span><span>{fr ? 'Autorisations' : 'Permissions'}</span><span /></div>{workspace.members.length ? workspace.members.map((member) => <div key={member.id} className="grid gap-3 border-t border-line p-4 first:border-0 md:grid-cols-[1.2fr_.7fr_1fr_auto] md:items-center"><div><strong className="text-sm text-green-deep">{member.memberName}</strong><p className="mt-1 text-xs text-ink-variant">{member.memberEmail}</p></div><div><span className="rounded-full bg-green/10 px-2.5 py-1 text-[9px] font-bold uppercase text-green">{member.role}</span>{member.title && <p className="mt-1 text-xs text-ink-variant">{member.title}</p>}</div><p className="text-xs leading-5 text-ink-variant">{member.permissions.map((item) => (fr ? permissionOptions.find((option) => option.value === item)?.fr : permissionOptions.find((option) => option.value === item)?.en) || item).join(' · ')}</p><button type="button" disabled={member.role === 'Owner'} onClick={() => void remove(member)} className="justify-self-start rounded-lg p-2 text-error hover:bg-error/10 disabled:cursor-not-allowed disabled:opacity-25 md:justify-self-end" aria-label={fr ? 'Retirer' : 'Remove'}><i className="ri-user-unfollow-line" /></button></div>) : <EmptyState title={fr ? 'Aucun membre' : 'No members'} />}</div></div>
        <div><Heading title={fr ? 'Demandes d’adhésion' : 'Membership requests'} count={pending.length} />{pending.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{pending.map((request) => <article key={request.id} className="rounded-2xl border border-line p-4"><strong className="text-sm text-green-deep">{request.memberName}</strong><p className="mt-1 text-xs text-ink-variant">{request.memberEmail}</p><p className="mt-3 rounded-xl bg-canvas p-3 text-sm leading-6 text-ink-variant">{request.message}</p><div className="mt-3 flex gap-2"><Button type="button" variant="secondary" onClick={() => void review(request.id, 'Approved')}>{fr ? 'Accepter' : 'Approve'}</Button><Button type="button" variant="tertiary" onClick={() => void review(request.id, 'Rejected')}>{fr ? 'Refuser' : 'Decline'}</Button></div></article>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-line p-7 text-center text-sm text-ink-variant">{fr ? 'Aucune demande en attente.' : 'No pending request.'}</p>}</div>
      </div>
      <form onSubmit={add} className="h-fit rounded-2xl border border-line bg-canvas/45 p-5"><p className="text-[9px] font-bold uppercase tracking-[.15em] text-red-link">{fr ? 'Ajouter un accès' : 'Grant access'}</p><h3 className="mt-2 font-display text-xl font-bold text-green-deep">{fr ? 'Nouveau membre' : 'New member'}</h3><div className="mt-5 space-y-4"><Field label={fr ? 'Membre HCBE' : 'HCBE member'} htmlFor="organization-member"><select id="organization-member" required className={inputClasses} value={candidateId} onChange={(event) => setCandidateId(event.target.value)}><option value="">{fr ? 'Sélectionner…' : 'Select…'}</option>{availableMembers.map((member) => <option key={member.id} value={member.id}>{member.firstName} {member.lastName} · {member.email}</option>)}</select></Field><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><Field label={fr ? 'Rôle' : 'Role'} htmlFor="organization-role"><select id="organization-role" className={inputClasses} value={role} onChange={(event) => setRole(event.target.value as AssociationMember['role'])}><option value="Manager">Manager</option><option value="Editor">Editor</option><option value="Member">Member</option></select></Field><Field label={fr ? 'Titre' : 'Title'} htmlFor="organization-title"><input id="organization-title" className={inputClasses} value={title} onChange={(event) => setTitle(event.target.value)} /></Field></div><fieldset><legend className="text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Autorisations' : 'Permissions'}</legend><div className="mt-3 space-y-2">{permissionOptions.map((option) => <label key={option.value} className="flex items-center gap-2 text-xs text-ink-variant"><input type="checkbox" className="accent-green" checked={selectedPermissions.includes(option.value)} onChange={(event) => setSelectedPermissions((current) => event.target.checked ? [...current, option.value] : current.filter((item) => item !== option.value))} />{fr ? option.fr : option.en}</label>)}</div></fieldset><Button type="submit" variant="secondary" className="w-full" disabled={!candidateId}>{fr ? 'Accorder l’accès' : 'Grant access'}</Button></div></form>
    </div>
  </section>;
}

function Heading({ title, count }: { title: string; count: number }) { return <div className="flex items-center gap-3"><h3 className="font-display text-xl font-bold text-green-deep">{title}</h3><span className="rounded-full bg-green/10 px-2.5 py-1 text-[10px] font-bold text-green">{count}</span><span className="h-px flex-1 bg-line" /></div>; }
