import { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { eventCommerceApi, type TicketTierInput } from '../../lib/api/event-commerce';
import type { EventPromoCode, EventTicketTier, TicketingDashboard } from '../../lib/api/types';
import { Button, Field, inputClasses } from '../ui';

const initialTier: TicketTierInput = { name: '', nameEn: '', description: '', descriptionEn: '', priceCents: 0, currency: 'cad', quantity: 100, maxPerOrder: 10, isActive: true, displayOrder: 0 };
const money = (value: number, currency: string, locale: string) => new Intl.NumberFormat(locale, { style: 'currency', currency: currency.toUpperCase() }).format(value / 100);

export function EventTicketingManager({ eventId }: { eventId: string }) {
  const { i18n } = useTranslation(); const fr = i18n.language.startsWith('fr'); const locale = fr ? 'fr-CA' : 'en-CA';
  const [tiers, setTiers] = useState<EventTicketTier[]>([]); const [promos, setPromos] = useState<EventPromoCode[]>([]); const [dashboard, setDashboard] = useState<TicketingDashboard>();
  const [tier, setTier] = useState<TicketTierInput>(initialTier); const [promo, setPromo] = useState({ code: '', percentOff: 10, maxRedemptions: 100 }); const [checkInCode, setCheckInCode] = useState('');
  const [editing, setEditing] = useState<string>(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const [tierResponse, promoResponse, dashboardResponse] = await Promise.all([eventCommerceApi.getAdminTiers(eventId), eventCommerceApi.getPromoCodes(eventId), eventCommerceApi.getDashboard(eventId)]);
    if (tierResponse.data) setTiers(tierResponse.data); if (promoResponse.data) setPromos(promoResponse.data); if (dashboardResponse.data) setDashboard(dashboardResponse.data);
  }, [eventId]);
  useEffect(() => { void load(); }, [load]);
  const act = async (operation: () => Promise<{ success: boolean; message?: string }>, success: string) => { setBusy(true); setError(''); try { const response = await operation(); if (!response.success) throw new Error(response.message); setMessage(success); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const saveTier = () => act(() => editing ? eventCommerceApi.updateTier(eventId, editing, tier) : eventCommerceApi.createTier(eventId, tier), fr ? 'Tarif enregistré.' : 'Ticket tier saved.').then(() => { setTier(initialTier); setEditing(undefined); });
  return <section className="overflow-hidden rounded-[24px] border border-line bg-background" aria-labelledby="ticket-admin-title">
    <header className="flex flex-col justify-between gap-4 border-b border-line bg-green/[.035] px-6 py-6 sm:flex-row sm:items-end"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-link">{fr ? 'Ventes et accès' : 'Sales and access'}</p><h2 id="ticket-admin-title" className="mt-1 font-display text-3xl font-bold text-green">{fr ? 'Billetterie' : 'Ticketing'}</h2><p className="mt-1 text-sm text-ink-variant">{fr ? 'Tarifs, codes promotionnels, ventes et contrôle des billets.' : 'Ticket tiers, promo codes, sales, and admission control.'}</p></div>{dashboard && <div className="grid grid-cols-3 gap-2 text-center"><span className="rounded-xl border border-line bg-surface px-3 py-2"><strong className="block text-lg text-green">{dashboard.ticketsSold}</strong><small className="text-[8px] uppercase">{fr ? 'vendus' : 'sold'}</small></span><span className="rounded-xl border border-line bg-surface px-3 py-2"><strong className="block text-lg text-green">{dashboard.checkedIn}</strong><small className="text-[8px] uppercase">{fr ? 'entrés' : 'checked in'}</small></span><span className="rounded-xl border border-line bg-surface px-3 py-2"><strong className="block text-lg text-green">{money(dashboard.grossRevenueCents, dashboard.currency, locale)}</strong><small className="text-[8px] uppercase">{fr ? 'brut' : 'gross'}</small></span></div>}</header>
    <div className="grid gap-8 p-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]">
      <div><h3 className="font-display text-xl font-bold text-green">{fr ? 'Tarifs' : 'Ticket tiers'}</h3><div className="mt-4 space-y-3">{tiers.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-line bg-surface p-4"><div><strong className="text-ink">{item.name}</strong><p className="mt-1 text-xs text-ink-variant">{money(item.priceCents, item.currency, locale)} · {item.soldQuantity}/{item.quantity} {fr ? 'vendus' : 'sold'} · {item.availableQuantity} {fr ? 'disponibles' : 'available'}</p></div><div className="flex gap-2"><button className="min-h-10 border border-line px-3 text-[9px] font-bold uppercase text-green" onClick={() => { setEditing(item.id); setTier({ name: item.name, nameEn: item.nameEn, description: item.description, descriptionEn: item.descriptionEn, priceCents: item.priceCents, currency: item.currency, quantity: item.quantity, maxPerOrder: item.maxPerOrder, salesStartUtc: item.salesStartUtc, salesEndUtc: item.salesEndUtc, isActive: item.isActive, displayOrder: item.displayOrder }); }}>{fr ? 'Modifier' : 'Edit'}</button><button className="min-h-10 border border-red/30 px-3 text-[9px] font-bold uppercase text-red-link" onClick={() => void act(() => eventCommerceApi.deleteTier(eventId, item.id), fr ? 'Tarif retiré.' : 'Tier removed.')}>{fr ? 'Retirer' : 'Remove'}</button></div></div>)}</div>
        <div className="mt-5 grid gap-4 rounded-2xl border border-line bg-surface p-5 sm:grid-cols-2"><Field label={fr ? 'Nom français' : 'French name'} htmlFor="tier-name"><input id="tier-name" value={tier.name} onChange={(e) => setTier({ ...tier, name: e.target.value })} className={inputClasses} /></Field><Field label={fr ? 'Nom anglais' : 'English name'} htmlFor="tier-name-en"><input id="tier-name-en" value={tier.nameEn} onChange={(e) => setTier({ ...tier, nameEn: e.target.value })} className={inputClasses} /></Field><Field label={fr ? 'Prix (CAD)' : 'Price (CAD)'} htmlFor="tier-price"><input id="tier-price" type="number" min="0" step="0.01" value={tier.priceCents / 100} onChange={(e) => setTier({ ...tier, priceCents: Math.round(Number(e.target.value) * 100) })} className={inputClasses} /></Field><Field label={fr ? 'Quantité' : 'Quantity'} htmlFor="tier-quantity"><input id="tier-quantity" type="number" min="1" value={tier.quantity} onChange={(e) => setTier({ ...tier, quantity: Number(e.target.value) })} className={inputClasses} /></Field><div className="sm:col-span-2 flex gap-3"><Button type="button" disabled={busy || !tier.name.trim()} onClick={() => void saveTier()}>{editing ? (fr ? 'Mettre à jour' : 'Update') : (fr ? 'Ajouter le tarif' : 'Add tier')}</Button>{editing && <Button type="button" variant="secondary" onClick={() => { setEditing(undefined); setTier(initialTier); }}>{fr ? 'Annuler' : 'Cancel'}</Button>}</div></div>
      </div>
      <aside className="space-y-7"><div><h3 className="font-display text-xl font-bold text-green">{fr ? 'Contrôle à l’entrée' : 'Admission control'}</h3><p className="mt-1 text-xs text-ink-variant">{fr ? 'Scannez le QR ou saisissez le code affiché sur le billet.' : 'Scan the QR or enter the code shown on the ticket.'}</p><div className="mt-3 flex gap-2"><input value={checkInCode} onChange={(e) => setCheckInCode(e.target.value.toUpperCase())} className={inputClasses} placeholder="TKT-…" /><Button type="button" disabled={!checkInCode || busy} onClick={() => void act(() => eventCommerceApi.checkIn(eventId, checkInCode), fr ? 'Billet validé.' : 'Ticket checked in.').then(() => setCheckInCode(''))}><i className="ri-qr-scan-2-line" /></Button></div></div>
        <div><h3 className="font-display text-xl font-bold text-green">{fr ? 'Codes promotionnels' : 'Promo codes'}</h3><div className="mt-3 flex gap-2"><input value={promo.code} onChange={(e) => setPromo({ ...promo, code: e.target.value.toUpperCase() })} className={inputClasses} placeholder="COMMUNAUTE10" /><input aria-label={fr ? 'Rabais en pourcentage' : 'Percent discount'} type="number" min="1" max="100" value={promo.percentOff} onChange={(e) => setPromo({ ...promo, percentOff: Number(e.target.value) })} className={`${inputClasses} max-w-24`} /><Button type="button" disabled={!promo.code || busy} onClick={() => void act(() => eventCommerceApi.createPromoCode(eventId, { ...promo, isActive: true }), fr ? 'Code créé.' : 'Promo code created.').then(() => setPromo({ code: '', percentOff: 10, maxRedemptions: 100 }))}><i className="ri-add-line" /></Button></div><div className="mt-3 flex flex-wrap gap-2">{promos.filter((item) => item.isActive).map((item) => <button key={item.id} type="button" title={fr ? 'Désactiver' : 'Disable'} onClick={() => void act(() => eventCommerceApi.deletePromoCode(eventId, item.id), fr ? 'Code désactivé.' : 'Promo disabled.')} className="rounded-full border border-gold/40 bg-gold/10 px-3 py-1 text-[10px] font-bold text-green">{item.code} · {item.percentOff}% ×</button>)}</div></div>
        {dashboard?.recentOrders.length ? <div><h3 className="font-display text-xl font-bold text-green">{fr ? 'Commandes récentes' : 'Recent orders'}</h3><div className="mt-3 divide-y divide-line border-y border-line">{dashboard.recentOrders.slice(0, 8).map((order) => <div key={order.id} className="flex justify-between gap-3 py-3 text-xs"><span><strong className="block text-ink">{order.buyerName}</strong><small className="text-ink-variant">{order.orderNumber} · {order.status}</small></span><strong className="text-green">{money(order.totalCents, order.currency, locale)}</strong></div>)}</div></div> : null}
      </aside>
    </div>{(message || error) && <p role="status" className={`border-t px-6 py-3 text-sm ${error ? 'border-red/30 text-red-link' : 'border-line text-green'}`}>{error || message}</p>}
  </section>;
}
