import { useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { membersApi } from '../../lib/api/members';
import type { MemberDuplicateCandidate, MemberImportResult, MemberImportRow } from '../../lib/api/types';
import { Button } from '../ui';

const fields: (keyof Omit<MemberImportRow, 'rowNumber'>)[] = ['firstName', 'lastName', 'email', 'phone', 'city', 'province', 'profession', 'expertise', 'interests', 'availability', 'zone'];
const aliases: Record<string, keyof Omit<MemberImportRow, 'rowNumber'>> = {
  firstname: 'firstName', prenom: 'firstName', lastname: 'lastName', nom: 'lastName', email: 'email', courriel: 'email', phone: 'phone', telephone: 'phone', city: 'city', ville: 'city', province: 'province', profession: 'profession', expertise: 'expertise', interests: 'interests', interets: 'interests', availability: 'availability', disponibilite: 'availability', zone: 'zone'
};
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z]/gi, '').toLowerCase();
function parseCsv(text: string): string[][] {
  const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false;
  for (let i = 0; i < text.length; i++) { const char = text[i]; if (char === '"') { if (quoted && text[i + 1] === '"') { cell += '"'; i++; } else quoted = !quoted; } else if (char === ',' && !quoted) { row.push(cell.trim()); cell = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[i + 1] === '\n') i++; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = ''; } else cell += char; }
  row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows;
}

export function MemberDataTools({ onChanged }: { onChanged: () => void | Promise<void> }) {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en'); const inputRef = useRef<HTMLInputElement>(null);
  const [rows, setRows] = useState<MemberImportRow[]>([]); const [result, setResult] = useState<MemberImportResult | null>(null); const [duplicates, setDuplicates] = useState<MemberDuplicateCandidate[] | null>(null); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState('');
  const copy = fr ? { eyebrow: 'Qualité des données', title: 'Registre fiable et portable', subtitle: 'Prévisualisez chaque import CSV, exportez le registre et fusionnez les fiches en double sans perdre leur historique.', export: 'Exporter CSV', import: 'Importer CSV', duplicates: 'Chercher les doublons', preview: 'Prévisualisation', ready: 'Prêtes', duplicate: 'Doublons', invalid: 'Invalides', commit: 'Importer les lignes valides', imported: 'membre(s) importé(s).', noDuplicates: 'Aucun doublon probable détecté.', confidence: 'Confiance', keepLeft: 'Conserver cette fiche', keepRight: 'Conserver l’autre fiche', mergeConfirm: 'Cette fusion est irréversible. Les dossiers liés seront transférés vers la fiche conservée. Continuer ?', error: 'Impossible de terminer cette opération.', csvError: 'Le fichier doit contenir les colonnes FirstName, LastName et Email.' } : { eyebrow: 'Data quality', title: 'Reliable, portable registry', subtitle: 'Preview every CSV import, export the registry and merge duplicate profiles without losing their history.', export: 'Export CSV', import: 'Import CSV', duplicates: 'Find duplicates', preview: 'Preview', ready: 'Ready', duplicate: 'Duplicates', invalid: 'Invalid', commit: 'Import valid rows', imported: 'member(s) imported.', noDuplicates: 'No likely duplicates detected.', confidence: 'Confidence', keepLeft: 'Keep this profile', keepRight: 'Keep the other profile', mergeConfirm: 'This merge cannot be undone. Linked records will move to the retained profile. Continue?', error: 'Unable to complete this operation.', csvError: 'The file must include FirstName, LastName and Email columns.' };
  const download = async () => { setBusy('export'); try { const { blob, fileName } = await membersApi.exportMembers(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName || 'hcbe-members.csv'; link.click(); URL.revokeObjectURL(url); } catch { setNotice(copy.error); } finally { setBusy(''); } };
  const chooseFile = async (file?: File) => { if (!file) return; setBusy('import'); setNotice(''); setDuplicates(null); try { const parsed = parseCsv((await file.text()).replace(/^\uFEFF/, '')); const header = parsed[0].map((item) => aliases[normalize(item)]); if (!header.includes('firstName') || !header.includes('lastName') || !header.includes('email')) throw new Error(copy.csvError); const mapped = parsed.slice(1).map((values, index) => { const item: MemberImportRow = { rowNumber: index + 2 }; header.forEach((key, column) => { if (key && fields.includes(key)) item[key] = values[column] || undefined; }); return item; }); const response = await membersApi.importMembers(mapped); if (!response.success || !response.data) throw new Error(response.message); setRows(mapped); setResult(response.data); } catch (error) { setNotice(error instanceof Error ? error.message : copy.error); } finally { setBusy(''); if (inputRef.current) inputRef.current.value = ''; } };
  const commit = async () => { setBusy('commit'); try { const response = await membersApi.importMembers(rows, true); if (!response.success || !response.data) throw new Error(); setResult(response.data); setNotice(`${response.data.importedRows} ${copy.imported}`); await onChanged(); } catch { setNotice(copy.error); } finally { setBusy(''); } };
  const scan = async () => { setBusy('duplicates'); setResult(null); try { const response = await membersApi.findDuplicates(); setDuplicates(response.data ?? []); } catch { setNotice(copy.error); } finally { setBusy(''); } };
  const merge = async (primaryMemberId: string, duplicateMemberId: string) => { if (!window.confirm(copy.mergeConfirm)) return; setBusy(duplicateMemberId); try { const response = await membersApi.mergeMembers(primaryMemberId, duplicateMemberId); if (!response.success) throw new Error(response.message); await scan(); await onChanged(); } catch (error) { setNotice(error instanceof Error ? error.message : copy.error); } finally { setBusy(''); } };
  return <section className="overflow-hidden rounded-[24px] border border-line bg-surface shadow-[0_14px_45px_rgba(0,59,27,.04)]">
    <div className="flex flex-wrap items-center justify-between gap-5 p-5 sm:p-7"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-red-link">{copy.eyebrow}</p><h2 className="mt-1 font-display text-2xl font-bold text-green-deep">{copy.title}</h2><p className="mt-2 text-sm leading-6 text-ink-variant">{copy.subtitle}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void download()} disabled={Boolean(busy)}><i className="ri-download-2-line" />{copy.export}</Button><Button variant="secondary" onClick={() => inputRef.current?.click()} disabled={Boolean(busy)}><i className="ri-upload-2-line" />{copy.import}</Button><Button onClick={() => void scan()} disabled={Boolean(busy)}><i className="ri-user-search-line" />{copy.duplicates}</Button><input ref={inputRef} className="sr-only" type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event.target.files?.[0])} /></div></div>
    {notice && <p role="status" className="border-t border-line bg-canvas/45 px-6 py-4 text-sm font-semibold text-green">{notice}</p>}
    {result && <div className="border-t border-line p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="font-display text-xl font-bold text-green-deep">{copy.preview}</h3><div className="mt-3 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-green/10 px-3 py-1.5 text-green">{result.preview.newRows} {copy.ready}</span><span className="rounded-full bg-gold/20 px-3 py-1.5 text-green-deep">{result.preview.duplicateRows} {copy.duplicate}</span><span className="rounded-full bg-error/10 px-3 py-1.5 text-error">{result.preview.invalidRows} {copy.invalid}</span></div></div>{result.importedRows === 0 && result.preview.newRows > 0 && <Button onClick={() => void commit()} disabled={Boolean(busy)}><i className="ri-database-2-line" />{copy.commit}</Button>}</div><div className="mt-5 max-h-72 divide-y divide-line overflow-y-auto rounded-2xl border border-line">{result.preview.rows.map((row) => <div key={row.rowNumber} className="grid gap-2 p-4 text-xs sm:grid-cols-[4rem_1fr_1fr_auto]"><span className="text-ink-variant">#{row.rowNumber}</span><strong className="text-ink">{row.displayName}</strong><span className="break-all text-ink-variant">{row.email}</span><span className={`font-bold ${row.status === 'Ready' ? 'text-green' : row.status === 'Duplicate' ? 'text-green-deep' : 'text-error'}`}>{row.issues.join(' · ') || copy.ready}</span></div>)}</div></div>}
    {duplicates && <div className="border-t border-line p-5 sm:p-7">{duplicates.length === 0 ? <p className="rounded-2xl border border-dashed border-line p-8 text-center text-sm text-ink-variant">{copy.noDuplicates}</p> : <div className="grid gap-4 xl:grid-cols-2">{duplicates.map((item) => <article key={`${item.primary.id}-${item.duplicate.id}`} className="rounded-2xl border border-line p-5"><div className="flex items-center justify-between gap-3"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-red-link">{copy.confidence}</span><strong className="font-display text-2xl text-green-deep">{item.score}%</strong></div><p className="mt-1 text-xs text-ink-variant">{item.reasons.join(' · ')}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[item.primary, item.duplicate].map((member) => <div key={member.id} className="rounded-xl bg-canvas/60 p-4"><strong className="block text-sm text-ink">{member.firstName} {member.lastName}</strong><span className="mt-1 block break-all text-xs text-ink-variant">{member.email}</span><span className="mt-1 block text-xs text-ink-variant">{member.phone || '—'} · {member.city || '—'}</span></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button variant="secondary" disabled={Boolean(busy)} onClick={() => void merge(item.primary.id, item.duplicate.id)}>{copy.keepLeft}</Button><Button variant="secondary" disabled={Boolean(busy)} onClick={() => void merge(item.duplicate.id, item.primary.id)}>{copy.keepRight}</Button></div></article>)}</div>}</div>}
  </section>;
}
