import { useEffect, useState } from 'react';
import { opportunitiesApi } from '../../../lib/api/opportunities';
import type { Opportunity, OpportunityApplication, UpsertOpportunityRequest } from '../../../lib/api/types';
import { AdminPageHeader } from '../../../components/admin/AdminPageHeader';
import { Button, Field, inputClasses } from '../../../components/ui';

const empty: UpsertOpportunityRequest = { title: '', description: '', type: 'Volunteer', organization: 'HCBE Canada', isRemote: false, status: 'Draft' };
export default function OpportunitiesAdminPage() {
  const [items, setItems] = useState<Opportunity[]>([]); const [applications, setApplications] = useState<OpportunityApplication[]>([]); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(false);
  const load = async () => { const [list, apps] = await Promise.all([opportunitiesApi.getAdmin(), opportunitiesApi.getApplications()]); setItems(list.data ?? []); setApplications(apps.data ?? []); };
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); const response = await opportunitiesApi.create(form); if (response.success) { setForm(empty); await load(); } setBusy(false); };
  const review = async (id: string, status: OpportunityApplication['status']) => { await opportunitiesApi.review(id, status); await load(); };
  return <div className="space-y-6"><AdminPageHeader title="Occasions et bénévolat" subtitle="Publiez des occasions utiles et suivez l’intérêt des membres." icon="ri-briefcase-4-line" count={items.length} />
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={create} className="rounded-2xl border border-line bg-surface p-6"><h2 className="font-display text-2xl font-bold text-green-deep">Nouvelle occasion</h2><div className="mt-5 space-y-4"><Field label="Titre" htmlFor="opp-title"><input id="opp-title" required className={inputClasses} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Description" htmlFor="opp-description"><textarea id="opp-description" required rows={5} className={inputClasses} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><div className="grid gap-3 sm:grid-cols-2"><select className={inputClasses} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Opportunity['type'] })}><option>Volunteer</option><option>Job</option><option>Business</option><option>Training</option><option>Community</option></select><select className={inputClasses} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Opportunity['status'] })}><option>Draft</option><option>Published</option></select><input placeholder="Organisation" required className={inputClasses} value={form.organization} onChange={(e) => setForm({ ...form, organization: e.target.value })} /><input placeholder="Lieu" className={inputClasses} value={form.location ?? ''} onChange={(e) => setForm({ ...form, location: e.target.value })} /><input placeholder="Compétences" className={inputClasses} value={form.skills ?? ''} onChange={(e) => setForm({ ...form, skills: e.target.value })} /><input placeholder="Lien externe" className={inputClasses} value={form.applyUrl ?? ''} onChange={(e) => setForm({ ...form, applyUrl: e.target.value })} /><input type="datetime-local" className={inputClasses} onChange={(e) => setForm({ ...form, deadlineUtc: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isRemote} onChange={(e) => setForm({ ...form, isRemote: e.target.checked })} /> À distance</label></div><Button type="submit" variant="primary" disabled={busy}>Créer</Button></div></form>
    <div className="space-y-5"><section className="rounded-2xl border border-line bg-surface p-5"><h2 className="font-display text-xl font-bold text-green-deep">Publications</h2><div className="mt-4 space-y-2">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-canvas/60 p-3"><div><strong className="text-sm text-green-deep">{item.title}</strong><p className="text-xs text-ink-variant">{item.type} · {item.status} · {item.applicationCount} candidature(s)</p></div>{item.status !== 'Closed' && <button className="text-xs font-bold text-error" onClick={() => void opportunitiesApi.close(item.id).then(load)}>Fermer</button>}</div>)}</div></section>
    <section className="rounded-2xl border border-line bg-surface p-5"><h2 className="font-display text-xl font-bold text-green-deep">Candidatures</h2><div className="mt-4 space-y-3">{applications.map((item) => <article key={item.id} className="rounded-xl border border-line p-4"><div className="flex justify-between"><div><strong className="text-sm text-green-deep">{item.memberName}</strong><p className="text-xs text-ink-variant">{item.opportunityTitle}</p></div><span className="text-[9px] font-bold uppercase text-red-link">{item.status}</span></div><p className="mt-3 text-sm text-ink-variant">{item.message}</p>{item.status === 'Submitted' && <div className="mt-3 flex gap-2"><Button type="button" variant="tertiary" onClick={() => void review(item.id, 'Declined')}>Refuser</Button><Button type="button" variant="secondary" onClick={() => void review(item.id, 'Accepted')}>Accepter</Button></div>}</article>)}</div></section></div></div>
  </div>;
}
