import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AdminPageHeader } from '../../../components/admin/AdminPageHeader';
import { Button, Field, inputClasses } from '../../../components/ui';
import { opportunitiesApi } from '../../../lib/api/opportunities';
import type { Opportunity, OpportunityApplication, UpsertOpportunityRequest } from '../../../lib/api/types';
import { localized } from '../../../lib/i18n/localized';

const empty: UpsertOpportunityRequest = { title: '', titleEn: '', description: '', descriptionEn: '', type: 'Volunteer', organization: 'HCBE Canada', isRemote: false, status: 'Draft' };
const types: Opportunity['type'][] = ['Volunteer', 'Job', 'Training', 'Business', 'Community'];

export default function OpportunitiesAdminPage() {
  const { i18n } = useTranslation(); const en = i18n.language.startsWith('en');
  const text = en ? {
    title: 'Opportunities & volunteering', subtitle: 'Publish opportunities, review candidates and recognize community involvement.', new: 'New publication', edit: 'Edit publication', desk: 'Candidate desk', publications: 'Publications', save: 'Save publication', update: 'Update', cancel: 'Cancel', empty: 'No application received yet.',
    titleFr: 'French title', titleEn: 'English title', descriptionFr: 'French description', descriptionEn: 'English description', organization: 'Organization', location: 'Location', region: 'Region', skills: 'Skills (separated by commas)', availability: 'Expected availability', commitment: 'Commitment / duration', requirementsFr: 'Requirements — French', requirementsEn: 'Requirements — English', benefitsFr: 'Benefits — French', benefitsEn: 'Benefits — English', contact: 'Contact email', link: 'External application link', start: 'Start', end: 'End', deadline: 'Application deadline', remote: 'Remote or hybrid opportunity',
    applications: 'applications', candidates: 'Candidates', pendingHours: 'hours to review', active: 'published', close: 'Close', modify: 'Edit', accept: 'Accept', decline: 'Decline', score: 'match', experience: 'Experience', documents: 'Supporting documents', availabilityApplicant: 'Availability', hours: 'Volunteer time', approve: 'Approve', reject: 'Reject', issue: 'Issue certificate', reissue: 'Update certificate', summary: 'Certificate contribution summary',
  } : {
    title: 'Occasions et bénévolat', subtitle: 'Publiez des occasions, évaluez les candidatures et reconnaissez l’engagement communautaire.', new: 'Nouvelle publication', edit: 'Modifier la publication', desk: 'Bureau des candidatures', publications: 'Publications', save: 'Enregistrer la publication', update: 'Mettre à jour', cancel: 'Annuler', empty: 'Aucune candidature reçue pour le moment.',
    titleFr: 'Titre français', titleEn: 'Titre anglais', descriptionFr: 'Description française', descriptionEn: 'Description anglaise', organization: 'Organisation', location: 'Lieu', region: 'Région', skills: 'Compétences (séparées par des virgules)', availability: 'Disponibilité attendue', commitment: 'Engagement / durée', requirementsFr: 'Profil recherché — français', requirementsEn: 'Profil recherché — anglais', benefitsFr: 'Avantages — français', benefitsEn: 'Avantages — anglais', contact: 'Courriel de contact', link: 'Lien de candidature externe', start: 'Début', end: 'Fin', deadline: 'Date limite de candidature', remote: 'Occasion à distance ou hybride',
    applications: 'candidatures', candidates: 'Candidatures', pendingHours: 'heures à valider', active: 'publiées', close: 'Fermer', modify: 'Modifier', accept: 'Accepter', decline: 'Refuser', score: 'compatible', experience: 'Expérience', documents: 'Documents justificatifs', availabilityApplicant: 'Disponibilité', hours: 'Temps de bénévolat', approve: 'Approuver', reject: 'Refuser', issue: 'Émettre l’attestation', reissue: 'Actualiser l’attestation', summary: 'Résumé de la contribution pour l’attestation',
  };
  const [items, setItems] = useState<Opportunity[]>([]); const [applications, setApplications] = useState<OpportunityApplication[]>([]);
  const [form, setForm] = useState<UpsertOpportunityRequest>(empty); const [editing, setEditing] = useState<string | null>(null);
  const [applicationFilter, setApplicationFilter] = useState('All'); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [certificateNotes, setCertificateNotes] = useState<Record<string, string>>({});
  const load = async () => { const [list, apps] = await Promise.all([opportunitiesApi.getAdmin(), opportunitiesApi.getApplications()]); setItems(list.data ?? []); setApplications(apps.data ?? []); };
  useEffect(() => { void load(); }, []);
  const pendingHours = applications.flatMap((item) => item.volunteerTimeEntries).filter((entry) => entry.status === 'Pending').length;
  const filteredApplications = applicationFilter === 'All' ? applications : applications.filter((item) => item.opportunityId === applicationFilter);
  const selectedPublication = useMemo(() => items.find((item) => item.id === applicationFilter), [items, applicationFilter]);
  const typeLabel = (type: Opportunity['type']) => ({ Volunteer: en ? 'Volunteering' : 'Bénévolat', Job: en ? 'Employment' : 'Emploi', Training: 'Formation', Business: en ? 'Business' : 'Affaires', Community: en ? 'Community' : 'Communauté' })[type];
  const statusLabel = (status: Opportunity['status']) => ({ Draft: en ? 'Draft' : 'Brouillon', Published: en ? 'Published' : 'Publiée', Closed: en ? 'Closed' : 'Fermée' })[status];
  const toLocal = (value?: string) => value ? new Date(value).toISOString().slice(0, 16) : '';
  const edit = (item: Opportunity) => { const { id: _id, applicationCount: _count, createdAt: _created, updatedAt: _updated, ...draft } = item; setForm(draft); setEditing(item.id); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setNotice(''); try { const result = editing ? await opportunitiesApi.update(editing, form) : await opportunitiesApi.create(form); if (result.success) { setForm(empty); setEditing(null); await load(); setNotice(en ? 'Publication saved.' : 'Publication enregistrée.'); } } catch (error) { setNotice(error instanceof Error ? error.message : 'Error'); } finally { setBusy(false); } };
  const review = async (id: string, status: OpportunityApplication['status']) => { setBusy(true); try { await opportunitiesApi.review(id, status); await load(); } finally { setBusy(false); } };
  const reviewHours = async (id: string, status: 'Approved' | 'Rejected') => { setBusy(true); try { await opportunitiesApi.reviewHours(id, status); await load(); } finally { setBusy(false); } };
  const issue = async (application: OpportunityApplication) => { setBusy(true); try { await opportunitiesApi.issueCertificate(application.id, certificateNotes[application.id]); await load(); } finally { setBusy(false); } };
  const downloadDocument = async (applicationId: string, documentId: string, fallbackName: string) => { const result = await opportunitiesApi.downloadDocument(applicationId, documentId); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.fileName ?? fallbackName; link.click(); URL.revokeObjectURL(url); };

  return <div className="space-y-7"><AdminPageHeader title={text.title} subtitle={text.subtitle} icon="ri-briefcase-4-line" count={items.length} />
    <section className="grid gap-3 sm:grid-cols-3"><Metric icon="ri-megaphone-line" value={items.filter((item) => item.status === 'Published').length} label={text.active} /><Metric icon="ri-user-search-line" value={applications.length} label={text.applications} /><Metric icon="ri-time-line" value={pendingHours} label={text.pendingHours} /></section>
    {notice && <p role="status" className="rounded-xl border border-gold/30 bg-gold/10 px-4 py-3 text-sm text-green-deep">{notice}</p>}
    <div className="grid min-w-0 gap-7 2xl:grid-cols-[minmax(390px,.78fr)_minmax(0,1.22fr)]">
      <form onSubmit={save} className="self-start rounded-[24px] border border-line bg-surface p-5 shadow-[0_14px_44px_rgba(0,59,27,.06)] sm:p-7 2xl:sticky 2xl:top-24"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-link">01 · {editing ? text.edit : text.new}</p><h2 className="mt-2 font-display text-2xl font-bold text-green-deep">{editing ? text.edit : text.new}</h2></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-gold/15 text-green"><i className="ri-edit-box-line text-xl" /></span></div>
        <div className="mt-6 space-y-4"><Pair><Field label={text.titleFr} htmlFor="opp-title"><input id="opp-title" required className={inputClasses} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label={text.titleEn} htmlFor="opp-title-en"><input id="opp-title-en" required className={inputClasses} value={form.titleEn ?? ''} onChange={(e) => setForm({ ...form, titleEn: e.target.value })} /></Field></Pair>
        <Pair><Field label={text.descriptionFr} htmlFor="opp-description"><textarea id="opp-description" required rows={5} className={inputClasses} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label={text.descriptionEn} htmlFor="opp-description-en"><textarea id="opp-description-en" required rows={5} className={inputClasses} value={form.descriptionEn ?? ''} onChange={(e) => setForm({ ...form, descriptionEn: e.target.value })} /></Field></Pair>
        <Pair><Field label={en ? 'Type' : 'Type'} htmlFor="opp-type"><select id="opp-type" className={inputClasses} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Opportunity['type'] })}>{types.map((value) => <option key={value} value={value}>{typeLabel(value)}</option>)}</select></Field><Field label={en ? 'Status' : 'Statut'} htmlFor="opp-status"><select id="opp-status" className={inputClasses} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Opportunity['status'] })}><option value="Draft">{statusLabel('Draft')}</option><option value="Published">{statusLabel('Published')}</option><option value="Closed">{statusLabel('Closed')}</option></select></Field></Pair>
        <Pair><Field label={text.organization} htmlFor="opp-org"><input id="opp-org" required className={inputClasses} value={form.organization} onChange={(e) => setForm({ ...form, organization: e.target.value })} /></Field><Field label={text.contact} htmlFor="opp-contact"><input id="opp-contact" type="email" className={inputClasses} value={form.contactEmail ?? ''} onChange={(e) => setForm({ ...form, contactEmail: e.target.value })} /></Field></Pair>
        <Pair><Field label={text.location} htmlFor="opp-location"><input id="opp-location" className={inputClasses} value={form.location ?? ''} onChange={(e) => setForm({ ...form, location: e.target.value })} /></Field><Field label={text.region} htmlFor="opp-region"><input id="opp-region" className={inputClasses} value={form.region ?? ''} onChange={(e) => setForm({ ...form, region: e.target.value })} /></Field></Pair>
        <Pair><Field label={text.skills} htmlFor="opp-skills"><input id="opp-skills" className={inputClasses} value={form.skills ?? ''} onChange={(e) => setForm({ ...form, skills: e.target.value })} /></Field><Field label={text.availability} htmlFor="opp-availability"><input id="opp-availability" className={inputClasses} value={form.availability ?? ''} onChange={(e) => setForm({ ...form, availability: e.target.value })} /></Field></Pair>
        <Field label={text.commitment} htmlFor="opp-commitment"><input id="opp-commitment" className={inputClasses} value={form.commitment ?? ''} onChange={(e) => setForm({ ...form, commitment: e.target.value })} /></Field>
        <Pair><Field label={text.requirementsFr} htmlFor="opp-requirements"><textarea id="opp-requirements" rows={3} className={inputClasses} value={form.requirements ?? ''} onChange={(e) => setForm({ ...form, requirements: e.target.value })} /></Field><Field label={text.requirementsEn} htmlFor="opp-requirements-en"><textarea id="opp-requirements-en" rows={3} className={inputClasses} value={form.requirementsEn ?? ''} onChange={(e) => setForm({ ...form, requirementsEn: e.target.value })} /></Field></Pair>
        <Pair><Field label={text.benefitsFr} htmlFor="opp-benefits"><textarea id="opp-benefits" rows={3} className={inputClasses} value={form.benefits ?? ''} onChange={(e) => setForm({ ...form, benefits: e.target.value })} /></Field><Field label={text.benefitsEn} htmlFor="opp-benefits-en"><textarea id="opp-benefits-en" rows={3} className={inputClasses} value={form.benefitsEn ?? ''} onChange={(e) => setForm({ ...form, benefitsEn: e.target.value })} /></Field></Pair>
        <Field label={text.link} htmlFor="opp-link"><input id="opp-link" type="url" className={inputClasses} value={form.applyUrl ?? ''} onChange={(e) => setForm({ ...form, applyUrl: e.target.value })} /></Field>
        <div className="grid gap-4 sm:grid-cols-3"><Field label={text.start} htmlFor="opp-start"><input id="opp-start" type="datetime-local" className={inputClasses} value={toLocal(form.startsAtUtc)} onChange={(e) => setForm({ ...form, startsAtUtc: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /></Field><Field label={text.end} htmlFor="opp-end"><input id="opp-end" type="datetime-local" className={inputClasses} value={toLocal(form.endsAtUtc)} onChange={(e) => setForm({ ...form, endsAtUtc: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /></Field><Field label={text.deadline} htmlFor="opp-deadline"><input id="opp-deadline" type="datetime-local" className={inputClasses} value={toLocal(form.deadlineUtc)} onChange={(e) => setForm({ ...form, deadlineUtc: e.target.value ? new Date(e.target.value).toISOString() : undefined })} /></Field></div>
        <label className="flex min-h-12 items-center gap-3 rounded-xl border border-line px-4 text-sm font-semibold text-green-deep"><input type="checkbox" checked={form.isRemote} onChange={(e) => setForm({ ...form, isRemote: e.target.checked })} /> {text.remote}</label>
        <div className="flex flex-col gap-2 sm:flex-row"><Button type="submit" variant="primary" disabled={busy}>{editing ? text.update : text.save}</Button>{editing && <Button type="button" variant="tertiary" onClick={() => { setEditing(null); setForm(empty); }}>{text.cancel}</Button>}</div></div>
      </form>

      <div className="min-w-0 space-y-6"><section className="rounded-[24px] border border-line bg-surface p-5 sm:p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-link">02 · {text.publications}</p><h2 className="mt-2 font-display text-2xl font-bold text-green-deep">{text.publications}</h2></div><span className="font-display text-3xl font-bold text-green-deep">{items.length}</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-2xl border border-line bg-canvas/50 p-4"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-gold/15 px-2.5 py-1 text-[8px] font-bold uppercase tracking-wider text-green-deep">{typeLabel(item.type)}</span><span className={`text-[8px] font-bold uppercase tracking-wider ${item.status === 'Published' ? 'text-green' : 'text-ink-muted'}`}>{statusLabel(item.status)}</span></div><h3 className="mt-3 line-clamp-2 font-display text-lg font-bold text-green-deep">{localized(item.title, item.titleEn, i18n.language)}</h3><p className="mt-2 text-xs text-ink-variant">{item.organization} · {item.applicationCount} {text.applications}</p><div className="mt-4 flex gap-3 border-t border-line pt-3"><button type="button" onClick={() => edit(item)} className="text-[9px] font-bold uppercase tracking-wider text-green"><i className="ri-edit-line mr-1" />{text.modify}</button>{item.status !== 'Closed' && <button type="button" onClick={() => void opportunitiesApi.close(item.id).then(load)} className="text-[9px] font-bold uppercase tracking-wider text-error"><i className="ri-close-circle-line mr-1" />{text.close}</button>}</div></article>)}</div></section>

      <section className="rounded-[24px] border border-line bg-surface p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-link">03 · {text.desk}</p><h2 className="mt-2 font-display text-2xl font-bold text-green-deep">{text.desk}</h2></div><select aria-label={text.publications} className={`${inputClasses} sm:max-w-[280px]`} value={applicationFilter} onChange={(e) => setApplicationFilter(e.target.value)}><option value="All">{en ? 'All publications' : 'Toutes les publications'}</option>{items.map((item) => <option key={item.id} value={item.id}>{localized(item.title, item.titleEn, i18n.language)}</option>)}</select></div>
        {selectedPublication && <p className="mt-3 text-xs text-ink-muted">{selectedPublication.applicationCount} {text.applications}</p>}
        {filteredApplications.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-line py-12 text-center text-sm text-ink-muted">{text.empty}</div> : <div className="mt-5 space-y-4">{filteredApplications.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-line"><header className="flex flex-col gap-4 bg-canvas/60 p-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-display text-xl font-bold text-green-deep">{item.memberName}</h3><a href={`mailto:${item.memberEmail}`} className="text-xs text-red-link">{item.memberEmail}</a><p className="mt-1 text-xs text-ink-muted">{localized(item.opportunityTitle, item.opportunityTitleEn, i18n.language)}</p></div><div className="flex items-center gap-3"><span className="rounded-xl bg-green px-3 py-2 text-sm font-bold text-white">{item.matchScore}% <small className="font-normal">{text.score}</small></span><span className="text-[9px] font-bold uppercase tracking-wider text-red-link">{item.status}</span></div></header><div className="space-y-4 p-4"><p className="text-sm leading-6 text-ink-variant">{item.message}</p><div className="grid gap-3 sm:grid-cols-2">{item.experience && <Info label={text.experience} value={item.experience} />}{item.availability && <Info label={text.availabilityApplicant} value={item.availability} />}</div>
          {item.documents.length > 0 && <div><p className="text-[9px] font-bold uppercase tracking-wider text-ink-muted">{text.documents}</p><div className="mt-2 flex flex-wrap gap-2">{item.documents.map((document) => <button type="button" key={document.id} onClick={() => void downloadDocument(item.id, document.id, document.fileName)} className="rounded-lg border border-line px-3 py-2 text-xs font-semibold text-green"><i className="ri-file-download-line mr-1" />{document.fileName}</button>)}</div></div>}
          {item.status !== 'Accepted' && item.status !== 'Declined' && <div className="flex flex-wrap gap-2"><Button type="button" variant="tertiary" disabled={busy} onClick={() => void review(item.id, 'Declined')}>{text.decline}</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => void review(item.id, 'Accepted')}>{text.accept}</Button></div>}
          {item.status === 'Accepted' && <div className="rounded-xl bg-canvas/60 p-4">{item.opportunityType === 'Volunteer' && <><div className="flex items-center justify-between"><p className="text-[9px] font-bold uppercase tracking-wider text-ink-muted">{text.hours}</p><strong className="text-green-deep">{item.approvedVolunteerHours} h</strong></div><div className="mt-3 space-y-2">{item.volunteerTimeEntries.map((entry) => <div key={entry.id} className="flex flex-col gap-2 rounded-lg border border-line bg-surface p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-green-deep">{entry.description}</p><p className="text-xs text-ink-muted">{new Date(entry.activityDate).toLocaleDateString()} · {entry.hours} h · {entry.status}</p></div>{entry.status === 'Pending' && <div className="flex gap-2"><button type="button" disabled={busy} onClick={() => void reviewHours(entry.id, 'Rejected')} className="text-[9px] font-bold uppercase text-error">{text.reject}</button><button type="button" disabled={busy} onClick={() => void reviewHours(entry.id, 'Approved')} className="rounded-lg bg-green px-3 py-2 text-[9px] font-bold uppercase text-white">{text.approve}</button></div>}</div>)}</div></>}
            <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input aria-label={text.summary} placeholder={text.summary} className={inputClasses} value={certificateNotes[item.id] ?? item.certificate?.contributionSummary ?? ''} onChange={(e) => setCertificateNotes({ ...certificateNotes, [item.id]: e.target.value })} /><Button type="button" variant="secondary" disabled={busy || (item.opportunityType === 'Volunteer' && item.approvedVolunteerHours <= 0 && !item.certificate)} onClick={() => void issue(item)}>{item.certificate ? text.reissue : text.issue}</Button></div>
          </div>}
        </div></article>)}</div>}
      </section></div>
    </div>
  </div>;
}

function Metric({ icon, value, label }: { icon: string; value: number; label: string }) { return <div className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center justify-between"><strong className="font-display text-3xl text-green-deep">{value}</strong><i className={`${icon} text-xl text-green`} /></div><p className="mt-2 text-[9px] font-bold uppercase tracking-[.14em] text-ink-muted">{label}</p></div>; }
function Pair({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-canvas/60 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-ink-muted">{label}</p><p className="mt-2 text-sm leading-5 text-ink-variant">{value}</p></div>; }
