# fly.toml app configuration file generated for hcbe-backend-jaunty-garden-7362 on 2026-07-09T18:23:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hcbe-backend-jaunty-garden-7362'
primary_region = 'yyz'

[build]

[deploy]
  release_command = 'dotnet HcbeApi.dll MigrateDatabase'
[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://+:8080'

[[mounts]]
  source = 'hcbe_data'
  destination = '/app/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health/ready'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
