import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AccountSecurityPanel } from '../../../components/security/AccountSecurityPanel';
import { AdminPageHeader } from '../../../components/admin/AdminPageHeader';
import { Button, Field, inputClasses } from '../../../components/ui';
import { securityApi } from '../../../lib/api/security';
import type { AuditLog, SecurityIncident, SecurityPosture } from '../../../lib/api/types';
import type { AdminUser } from '../../../lib/api/types';
import { usersApi } from '../../../lib/api/users';

const emptyIncident = { title: '', description: '', severity: 'Medium', personalDataInvolved: false, estimatedPeopleAffected: undefined as number | undefined, harmRiskAssessment: '' };

export default function AdminSecurityPage() {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en');
  const locale = fr ? 'fr-CA' : 'en-CA';
  const [posture, setPosture] = useState<SecurityPosture | null>(null); const [incidents, setIncidents] = useState<SecurityIncident[]>([]); const [audit, setAudit] = useState<AuditLog[]>([]);
  const [admins, setAdmins] = useState<AdminUser[]>([]);
  const [form, setForm] = useState(emptyIncident); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const copy = fr ? {
    title: 'Centre de sécurité', subtitle: 'Authentification, appareils, incidents et contrôles opérationnels de la Loi 25.', posture: 'Posture de sécurité',
    admins: 'Administrateurs actifs', mfa: 'Administrateurs avec MFA', sessions: 'Sessions actives', incidents: 'Incidents ouverts', reviews: 'Accès à réviser',
    incidentRegister: 'Registre des incidents', newIncident: 'Signaler un incident', noIncident: 'Aucun incident ouvert.', description: 'Description', severity: 'Gravité', titleLabel: 'Titre', data: 'Renseignements personnels concernés', affected: 'Personnes potentiellement touchées', risk: 'Évaluation du risque de préjudice grave', save: 'Inscrire au registre',
    contain: 'Marquer contenu', resolve: 'Résoudre', audit: 'Actions sensibles récentes', actor: 'Acteur', action: 'Action', date: 'Date', error: 'Impossible de charger le centre de sécurité.', procedure: 'Procédure intégrée', procedureText: '1. Signaler et qualifier · 2. Contenir · 3. Évaluer le risque de préjudice · 4. Aviser la CAI et les personnes lorsque requis · 5. Corriger, documenter et fermer.',
    access: 'Revue trimestrielle des accès', role: 'Rôle', lastLogin: 'Dernière connexion', confirmAccess: 'Accès confirmé', never: 'Jamais', caiRequired: 'Avis CAI requis', caiNotified: 'CAI avisée', peopleNotified: 'Personnes avisées',
  } : {
    title: 'Security centre', subtitle: 'Authentication, devices, incidents and operational Law 25 controls.', posture: 'Security posture',
    admins: 'Active administrators', mfa: 'Administrators with MFA', sessions: 'Active sessions', incidents: 'Open incidents', reviews: 'Access reviews due',
    incidentRegister: 'Incident register', newIncident: 'Report an incident', noIncident: 'No open incidents.', description: 'Description', severity: 'Severity', titleLabel: 'Title', data: 'Personal information involved', affected: 'People potentially affected', risk: 'Risk of serious harm assessment', save: 'Add to register',
    contain: 'Mark contained', resolve: 'Resolve', audit: 'Recent sensitive actions', actor: 'Actor', action: 'Action', date: 'Date', error: 'Unable to load the security centre.', procedure: 'Integrated procedure', procedureText: '1. Report and assess · 2. Contain · 3. Assess serious-harm risk · 4. Notify the CAI and individuals when required · 5. Correct, document and close.',
    access: 'Quarterly access review', role: 'Role', lastLogin: 'Last sign-in', confirmAccess: 'Confirm access', never: 'Never', caiRequired: 'CAI notice required', caiNotified: 'CAI notified', peopleNotified: 'Individuals notified',
  };
  const load = async () => { try { const [a,b,c,d] = await Promise.all([securityApi.getPosture(), securityApi.getIncidents(), securityApi.getAudit(), usersApi.getAdminUsers().catch(() => ({ success: false, data: [] as AdminUser[] }))]); setPosture(a.data ?? null); setIncidents(b.data ?? []); setAudit(c.data?.items ?? []); setAdmins(d.data ?? []); } catch { setError(copy.error); } };
  useEffect(() => { void load(); }, [fr]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await securityApi.createIncident(form); if (!response.success) throw new Error(); setForm(emptyIncident); setShowForm(false); await load(); } catch { setError(copy.error); } finally { setBusy(false); } };
  const update = async (id: string, status: string) => { setBusy(true); try { await securityApi.updateIncident(id, { status }); await load(); } finally { setBusy(false); } };
  const updateIncident = async (id: string, data: Partial<SecurityIncident>) => { setBusy(true); try { await securityApi.updateIncident(id, data); await load(); } finally { setBusy(false); } };
  const cards = [[copy.admins, posture?.activeAdmins ?? 0, 'ri-admin-line'], [copy.mfa, `${posture?.adminsWithMfa ?? 0}/${posture?.activeAdmins ?? 0}`, 'ri-shield-keyhole-line'], [copy.sessions, posture?.activeSessions ?? 0, 'ri-device-line'], [copy.incidents, posture?.openIncidents ?? 0, 'ri-alarm-warning-line'], [copy.reviews, posture?.overdueAccessReviews ?? 0, 'ri-user-follow-line']];
  const localizeValue = (value: string) => {
    if (!fr) return value;
    return ({ Low: 'Faible', Medium: 'Moyenne', High: 'Élevée', Critical: 'Critique', Open: 'Ouvert', Contained: 'Contenu', Resolved: 'Résolu', Added: 'Ajout', Modified: 'Modification', Deleted: 'Suppression', 'super-admin': 'Super administrateur', 'community-manager': 'Gestionnaire communautaire', 'content-editor': 'Éditeur de contenu', 'finance-manager': 'Responsable des finances', 'privacy-officer': 'Responsable de la protection des renseignements', 'security-auditor': 'Auditeur de sécurité' } as Record<string, string>)[value] ?? value;
  };
  return <div className="space-y-6 pb-10"><AdminPageHeader icon="ri-shield-keyhole-line" title={copy.title} subtitle={copy.subtitle} count={posture?.openIncidents ?? 0} />
    {error && <div role="alert" className="rounded-xl border border-error/25 bg-error/5 p-4 text-error">{error}</div>}
    <section><div className="mb-4 flex items-center gap-3"><span className="h-px w-8 bg-gold"/><h2 className="text-[11px] font-bold uppercase tracking-[.16em] text-green">{copy.posture}</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,icon]) => <article key={String(label)} className="rounded-2xl border border-line bg-surface p-5 shadow-[0_12px_35px_rgba(0,59,27,.04)]"><i className={`${icon} text-xl text-green`} /><strong className="mt-5 block font-display text-3xl text-green-deep">{value}</strong><span className="mt-1 block text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{label}</span></article>)}</div></section>
    <AccountSecurityPanel />
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div className="rounded-[24px] border border-line bg-surface p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-red-link">Loi 25</p><h2 className="mt-1 font-display text-2xl font-bold text-green-deep">{copy.incidentRegister}</h2></div><Button onClick={() => setShowForm(!showForm)}><i className="ri-add-line" />{copy.newIncident}</Button></div>
      {showForm && <form onSubmit={create} className="mt-6 grid gap-4 rounded-2xl border border-gold/35 bg-gold/[.04] p-5 sm:grid-cols-2"><Field label={copy.titleLabel} htmlFor="incident-title" required className="sm:col-span-2"><input id="incident-title" required maxLength={200} className={inputClasses} value={form.title} onChange={e => setForm({...form,title:e.target.value})}/></Field><Field label={copy.description} htmlFor="incident-description" required className="sm:col-span-2"><textarea id="incident-description" required rows={4} className={inputClasses} value={form.description} onChange={e => setForm({...form,description:e.target.value})}/></Field><Field label={copy.severity} htmlFor="incident-severity"><select id="incident-severity" className={inputClasses} value={form.severity} onChange={e => setForm({...form,severity:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x} value={x}>{localizeValue(x)}</option>)}</select></Field><Field label={copy.affected} htmlFor="incident-affected"><input id="incident-affected" type="number" min="0" className={inputClasses} value={form.estimatedPeopleAffected ?? ''} onChange={e => setForm({...form,estimatedPeopleAffected:e.target.value ? Number(e.target.value) : undefined})}/></Field><label className="flex items-center gap-3 text-sm sm:col-span-2"><input type="checkbox" className="h-5 w-5 accent-green" checked={form.personalDataInvolved} onChange={e => setForm({...form,personalDataInvolved:e.target.checked})}/>{copy.data}</label><Field label={copy.risk} htmlFor="incident-risk" className="sm:col-span-2"><textarea id="incident-risk" rows={3} className={inputClasses} value={form.harmRiskAssessment} onChange={e => setForm({...form,harmRiskAssessment:e.target.value})}/></Field><Button type="submit" disabled={busy} className="sm:col-span-2 sm:justify-self-start">{copy.save}</Button></form>}
      <div className="mt-6 space-y-3">{incidents.length===0?<p className="rounded-2xl border border-dashed border-line p-8 text-center text-sm text-ink-variant">{copy.noIncident}</p>:incidents.map(item=><article key={item.id} className="rounded-2xl border border-line p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-[.13em] text-red-link">{item.referenceNumber} · {localizeValue(item.severity)}</span><h3 className="mt-2 font-display text-xl font-bold text-green-deep">{item.title}</h3><p className="mt-2 text-sm leading-6 text-ink-variant">{item.description}</p></div><span className="rounded-full bg-green/8 px-3 py-1 text-[10px] font-bold uppercase text-green">{localizeValue(item.status)}</span></div><div className="mt-4 flex flex-wrap gap-2">{item.status!=='Contained'&&<Button variant="secondary" onClick={()=>update(item.id,'Contained')} disabled={busy}>{copy.contain}</Button>}<Button variant="secondary" onClick={()=>update(item.id,'Resolved')} disabled={busy}>{copy.resolve}</Button>{item.personalDataInvolved&&!item.caiNotificationRequired&&<Button variant="secondary" onClick={()=>updateIncident(item.id,{caiNotificationRequired:true})} disabled={busy}>{copy.caiRequired}</Button>}{item.caiNotificationRequired&&!item.caiNotifiedAtUtc&&<Button variant="secondary" onClick={()=>updateIncident(item.id,{caiNotifiedAtUtc:new Date().toISOString()})} disabled={busy}>{copy.caiNotified}</Button>}{item.personalDataInvolved&&!item.individualsNotifiedAtUtc&&<Button variant="secondary" onClick={()=>updateIncident(item.id,{individualsNotifiedAtUtc:new Date().toISOString()})} disabled={busy}>{copy.peopleNotified}</Button>}</div></article>)}</div>
    </div><aside className="space-y-5"><div className="rounded-[24px] bg-green-deep p-6 text-white"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-gold/30 bg-gold/10 text-xl text-gold"><i className="ri-route-line" /></span><h2 className="mt-5 font-display text-2xl font-bold">{copy.procedure}</h2><p className="mt-3 text-sm leading-7 text-white/72">{copy.procedureText}</p></div><div className="rounded-[24px] border border-line bg-surface p-5"><h2 className="font-display text-xl font-bold text-green-deep">{copy.audit}</h2><div className="mt-4 divide-y divide-line">{audit.slice(0,12).map(item=><div key={item.id} className="py-3"><strong className="block text-xs text-ink">{localizeValue(item.action)}</strong><span className="mt-1 block text-[11px] text-ink-variant">{item.userEmail || copy.actor} · {new Date(item.createdAtUtc).toLocaleString(locale)}</span></div>)}</div></div></aside></section>
    <section className="rounded-[24px] border border-line bg-surface p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-red-link">{fr?'Moindre privilège':'Least privilege'}</p><h2 className="mt-1 font-display text-2xl font-bold text-green-deep">{copy.access}</h2></div><span className="rounded-full bg-gold/15 px-3 py-1 text-xs font-bold text-green">{admins.length}</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{admins.map(admin=><article key={admin.id} className="flex flex-col gap-4 rounded-2xl border border-line p-5 sm:flex-row sm:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-green text-sm font-bold text-white">{(admin.firstName?.[0]||admin.email[0]).toUpperCase()}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-ink">{admin.firstName} {admin.lastName}</strong><span className="block truncate text-xs text-ink-variant">{admin.email}</span><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-bold uppercase"><span className="rounded-full bg-surface-container px-2 py-1 text-green">{localizeValue(admin.adminRole)}</span><span className={`rounded-full px-2 py-1 ${admin.mfaEnabled?'bg-green/10 text-green':'bg-error/10 text-error'}`}>MFA {admin.mfaEnabled?'✓':'—'}</span></div><p className="mt-2 text-[11px] text-ink-variant">{copy.lastLogin}: {admin.lastLoginAtUtc?new Date(admin.lastLoginAtUtc).toLocaleDateString(locale):copy.never}</p></div><Button variant="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await securityApi.reviewAccess(admin.id,'Retain');await load();}finally{setBusy(false);}}}>{copy.confirmAccess}</Button></article>)}</div></section>
  </div>;
}
