import { useEffect, useState } from 'react';
import { opportunitiesApi } from '../../../lib/api/opportunities';
import type { Opportunity, OpportunityApplication } from '../../../lib/api/types';
import { Button, Field, inputClasses } from '../../../components/ui';
import { engagementApi } from '../../../lib/api/engagement';

export default function MemberOpportunitiesPanel() {
  const [items, setItems] = useState<Opportunity[]>([]); const [mine, setMine] = useState<OpportunityApplication[]>([]); const [selected, setSelected] = useState<Opportunity | null>(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [savedIds, setSavedIds] = useState<Set<string>>(new Set());
  const load = async () => { const [list, applications, saved] = await Promise.all([opportunitiesApi.getPublished(), opportunitiesApi.getMine(), engagementApi.getSaved()]); setItems(list.data ?? []); setMine(applications.data ?? []); setSavedIds(new Set((saved.data ?? []).filter((item) => item.entityType === 'Opportunity').map((item) => item.entityId))); };
  useEffect(() => { void load(); }, []); const applied = new Set(mine.map((item) => item.opportunityId));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); const result = await opportunitiesApi.apply(selected.id, message); if (result.success) { setSelected(null); setMessage(''); await load(); } setBusy(false); };
  const toggleSaved = async (id: string) => { if (savedIds.has(id)) await engagementApi.removeSaved('Opportunity', id); else await engagementApi.save('Opportunity', id); await load(); };
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-[26px] bg-green-deep p-6 text-white sm:p-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full border-[34px] border-gold/[.09]" /><p className="relative text-[9px] font-bold uppercase tracking-[.18em] text-gold">Agir dans la communauté</p><h2 className="relative mt-3 font-display text-3xl font-bold text-white sm:text-4xl">Occasions et bénévolat</h2><p className="relative mt-3 max-w-2xl text-sm leading-6 text-green-dim">Mettez votre expérience au service de projets utiles, découvrez des emplois et développez de nouvelles compétences.</p></section>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="flex flex-col rounded-[22px] border border-line bg-surface p-5 shadow-[0_12px_32px_rgba(0,59,27,.05)]"><div className="flex justify-between gap-3"><span className="rounded-full bg-gold/15 px-3 py-1 text-[9px] font-bold uppercase text-green-deep">{item.type}</span><button type="button" aria-label={savedIds.has(item.id) ? 'Retirer des favoris' : 'Enregistrer'} onClick={() => void toggleSaved(item.id)} className={`flex h-9 w-9 items-center justify-center rounded-xl border transition ${savedIds.has(item.id) ? 'border-gold bg-gold text-green-deep' : 'border-line text-green hover:border-green/30'}`}><i className={savedIds.has(item.id) ? 'ri-bookmark-fill' : 'ri-bookmark-line'} /></button></div><h3 className="mt-4 font-display text-xl font-bold text-green-deep">{item.title}</h3><p className="mt-1 text-xs text-red-link">{item.organization}</p><p className="mt-3 line-clamp-4 flex-1 text-sm leading-6 text-ink-variant">{item.description}</p><div className="mt-4 border-t border-line pt-4 text-xs text-ink-variant">{item.location || 'Canada'}{item.deadlineUtc ? ` · avant le ${new Date(item.deadlineUtc).toLocaleDateString('fr-CA')}` : ''}</div>{item.applyUrl ? <a href={item.applyUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center justify-center rounded-xl bg-green px-4 text-[10px] font-bold uppercase tracking-[.11em] text-white">Consulter</a> : <Button type="button" variant="secondary" className="mt-4" disabled={applied.has(item.id)} onClick={() => setSelected(item)}>{applied.has(item.id) ? 'Candidature envoyée' : 'Je suis intéressé(e)'}</Button>}</article>)}</div>
  {mine.length > 0 && <section><h3 className="font-display text-xl font-bold text-green-deep">Mes candidatures</h3><div className="mt-3 flex flex-wrap gap-2">{mine.map((item) => <span key={item.id} className="rounded-full border border-line bg-surface px-4 py-2 text-xs">{item.opportunityTitle} · <strong>{item.status}</strong></span>)}</div></section>}
  {selected && <div className="fixed inset-0 z-[90] grid place-items-center bg-green-deep/80 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-[24px] bg-surface p-6"><h3 className="font-display text-2xl font-bold text-green-deep">{selected.title}</h3><div className="mt-5"><Field label="Présentez votre intérêt" htmlFor="opportunity-message"><textarea id="opportunity-message" autoFocus required minLength={20} rows={6} className={inputClasses} value={message} onChange={(e) => setMessage(e.target.value)} /></Field></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="tertiary" onClick={() => setSelected(null)}>Annuler</Button><Button type="submit" variant="secondary" disabled={busy}>Envoyer</Button></div></form></div>}</div>;
}
