import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { associationsApi } from '../../../lib/api/associations';
import type { Association, AssociationClaim } from '../../../lib/api/types';
import { Button, Field, inputClasses } from '../../../components/ui';

export default function MemberAssociationsPanel() {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en');
  const [all, setAll] = useState<Association[]>([]); const [managed, setManaged] = useState<Association[]>([]); const [claims, setClaims] = useState<AssociationClaim[]>([]);
  const [selected, setSelected] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { const [catalog, mine, requests] = await Promise.all([associationsApi.getAssociations(), associationsApi.getManagedAssociations(), associationsApi.getMyClaims()]); setAll(catalog.data ?? []); setManaged(mine.data ?? []); setClaims(requests.data ?? []); };
  useEffect(() => { void load(); }, []);
  const claimedIds = useMemo(() => new Set([...managed.map((item) => item.id), ...claims.filter((item) => item.status === 'Pending').map((item) => item.associationId)]), [managed, claims]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); const response = await associationsApi.claimAssociation(selected, message); setNotice(response.success ? (fr ? 'Demande envoyée au HCBE.' : 'Request sent to HCBE.') : response.message ?? 'Error'); if (response.success) { setSelected(''); setMessage(''); await load(); } setBusy(false); };
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-[26px] bg-green-deep p-6 text-white sm:p-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full border-[34px] border-gold/[.09]" /><div className="relative max-w-2xl"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-gold">{fr ? 'Associations partenaires' : 'Partner associations'}</p><h2 className="mt-3 font-display text-3xl font-bold text-white sm:text-4xl">{fr ? 'Gérez votre présence locale.' : 'Manage your local presence.'}</h2><p className="mt-3 text-sm leading-6 text-green-dim">{fr ? 'Demandez la gestion d’une association, puis gardez sa fiche publique à jour après validation.' : 'Request management access, then keep its public profile up to date after approval.'}</p></div></section>
    {managed.length > 0 && <section><div className="mb-4 flex items-center gap-3"><h3 className="font-display text-2xl font-bold text-green-deep">{fr ? 'Mes associations' : 'My associations'}</h3><span className="h-px flex-1 bg-line" /></div><div className="grid gap-4 lg:grid-cols-2">{managed.map((item) => <ManagedAssociation key={item.id} item={item} fr={fr} onSaved={load} />)}</div></section>}
    <section className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><form onSubmit={submit} className="rounded-[24px] border border-line bg-surface p-6 sm:p-7"><h3 className="font-display text-2xl font-bold text-green-deep">{fr ? 'Représentez-vous une association ?' : 'Do you represent an association?'}</h3><p className="mt-2 text-sm leading-6 text-ink-variant">{fr ? 'Le comité vérifie chaque demande avant de donner accès à la fiche.' : 'The committee verifies every request before granting profile access.'}</p><div className="mt-5 space-y-4"><Field label={fr ? 'Association' : 'Association'} htmlFor="association-claim"><select id="association-claim" required className={inputClasses} value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">—</option>{all.filter((item) => !claimedIds.has(item.id)).map((item) => <option key={item.id} value={item.id}>{item.name} — {item.city}</option>)}</select></Field><Field label={fr ? 'Votre rôle et un moyen de vérification' : 'Your role and verification details'} htmlFor="claim-message"><textarea id="claim-message" required minLength={20} rows={5} className={inputClasses} value={message} onChange={(e) => setMessage(e.target.value)} /></Field>{notice && <p className="text-sm text-green">{notice}</p>}<Button type="submit" variant="secondary" disabled={busy || !selected}>{fr ? 'Envoyer la demande' : 'Submit request'}</Button></div></form>
    <div className="rounded-[24px] border border-line bg-canvas/50 p-6"><h3 className="font-display text-xl font-bold text-green-deep">{fr ? 'Suivi des demandes' : 'Request status'}</h3><div className="mt-4 space-y-3">{claims.length === 0 ? <p className="text-sm text-ink-variant">{fr ? 'Aucune demande.' : 'No request yet.'}</p> : claims.map((claim) => <article key={claim.id} className="rounded-xl border border-line bg-surface p-4"><div className="flex justify-between gap-3"><strong className="text-sm text-green-deep">{claim.associationName}</strong><span className="text-[9px] font-bold uppercase text-red-link">{claim.status}</span></div>{claim.adminNotes && <p className="mt-2 text-xs text-ink-variant">{claim.adminNotes}</p>}</article>)}</div></div></section></div>;
}

function ManagedAssociation({ item, fr, onSaved }: { item: Association; fr: boolean; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState(item); const [busy, setBusy] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); await associationsApi.updateManagedAssociation(item.id, { name: form.name, description: form.description, province: form.province, city: form.city, contact: form.contact, phone: form.phone, website: form.website, domains: form.domains }); await onSaved(); setBusy(false); };
  return <form onSubmit={save} className="rounded-[24px] border border-line bg-surface p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-green text-xl text-white"><i className="ri-building-2-line" /></span><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-red-link">{fr ? 'Accès approuvé' : 'Approved access'}</p><h4 className="font-display text-xl font-bold text-green-deep">{item.name}</h4></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input aria-label="Name" className={inputClasses} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input aria-label="Website" placeholder="Website" className={inputClasses} value={form.website ?? ''} onChange={(e) => setForm({ ...form, website: e.target.value })} /><input aria-label="City" className={inputClasses} value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /><input aria-label="Province" className={inputClasses} value={form.province} onChange={(e) => setForm({ ...form, province: e.target.value })} /><textarea aria-label="Description" rows={4} className={`${inputClasses} sm:col-span-2`} value={form.description ?? ''} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><Button type="submit" variant="tertiary" className="mt-4" disabled={busy}>{fr ? 'Enregistrer' : 'Save'}</Button></form>;
}
