import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { notificationsApi } from '../../../lib/api/notifications';
import type { AppNotification } from '../../../lib/api/types';
import { Button } from '../../../components/ui';

export default function MemberNotificationsPanel({ onUnreadChange }: { onUnreadChange?: (count: number) => void }) {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en');
  const [items, setItems] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { const response = await notificationsApi.getAll(); const next = response.data ?? []; setItems(next); onUnreadChange?.(next.filter((item) => !item.isRead).length); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const read = async (item: AppNotification) => { if (!item.isRead) await notificationsApi.markRead(item.id); await load(); };
  const readAll = async () => { await notificationsApi.markAllRead(); await load(); };
  return <div className="overflow-hidden rounded-[26px] border border-line bg-surface shadow-[0_16px_45px_rgba(0,59,27,.06)]"><header className="relative overflow-hidden bg-green-deep px-6 py-7 text-white sm:px-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full border-[34px] border-gold/[.09]" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-gold">{fr ? 'Fil personnel' : 'Personal feed'}</p><h2 className="mt-3 font-display text-3xl font-bold">{fr ? 'Mes notifications' : 'My notifications'}</h2><p className="mt-2 text-sm text-green-dim">{fr ? 'Les mises à jour qui concernent uniquement votre compte.' : 'Updates related only to your account.'}</p></div><Button type="button" variant="tertiary" className="border-white/20 text-white" onClick={readAll}>{fr ? 'Tout marquer comme lu' : 'Mark all read'}</Button></div></header><div className="divide-y divide-line">{loading ? <p className="p-8 text-center text-ink-variant"><i className="ri-loader-4-line animate-spin" /></p> : items.length === 0 ? <div className="p-10 text-center"><i className="ri-notification-off-line text-3xl text-green" /><p className="mt-3 text-sm text-ink-variant">{fr ? 'Vous êtes à jour.' : 'You are all caught up.'}</p></div> : items.map((item) => { const body = <div className="flex gap-4"><span className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.isRead ? 'bg-canvas text-ink-variant' : 'bg-gold/20 text-green'}`}><i className="ri-notification-3-line" /></span><span className="min-w-0"><strong className="block text-sm text-green-deep">{item.title}</strong><span className="mt-1 block text-sm leading-6 text-ink-variant">{item.message}</span><small className="mt-2 block text-[10px] text-ink-variant">{new Date(item.createdAt).toLocaleString(fr ? 'fr-CA' : 'en-CA')}</small></span></div>; return item.link ? <Link key={item.id} to={item.link} onClick={() => void read(item)} className={`block p-5 transition hover:bg-green/[.025] ${item.isRead ? '' : 'border-l-4 border-l-gold bg-gold/[.035]'}`}>{body}</Link> : <button key={item.id} onClick={() => void read(item)} className={`block w-full p-5 text-left transition hover:bg-green/[.025] ${item.isRead ? '' : 'border-l-4 border-l-gold bg-gold/[.035]'}`}>{body}</button>; })}</div></div>;
}
