import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { communityApi } from '../../../lib/api/community';
import type { MentorshipJourney } from '../../../lib/api/types';
import { Button, inputClasses } from '../../../components/ui';

export default function MentorshipJourneyPanel({ matchId }: { matchId: string }) {
  const { t } = useTranslation();
  const [journey, setJourney] = useState<MentorshipJourney | null>(null); const [goal, setGoal] = useState(''); const [summary, setSummary] = useState(''); const [rating, setRating] = useState(5); const [support, setSupport] = useState(false); const [busy, setBusy] = useState(false);
  const load = async () => { const response = await communityApi.getJourney(matchId); setJourney(response.data ?? null); };
  useEffect(() => { void load(); }, [matchId]);
  if (!journey) return null;
  const addGoal = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); if ((await communityApi.addGoal(matchId, goal)).success) { setGoal(''); await load(); } setBusy(false); };
  const checkIn = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); if ((await communityApi.addCheckIn(matchId, summary, rating, support)).success) { setSummary(''); setSupport(false); await load(); } setBusy(false); };
  return <section className="mt-4 overflow-hidden rounded-2xl border border-green/15 bg-green/[.035]"><header className="flex items-center justify-between border-b border-line p-4"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-red-link">{t('public.member.journey.eyebrow')}</p><h5 className="font-display text-lg font-bold text-green-deep">{t('public.member.journey.title')}</h5></div><span className="rounded-full bg-green px-3 py-1 text-[9px] font-bold uppercase text-white">{journey.goals.filter((item) => item.status === 'Completed').length}/{journey.goals.length}</span></header><div className="grid gap-5 p-4 lg:grid-cols-2"><div><form onSubmit={addGoal} className="flex gap-2"><input required minLength={3} aria-label={t('public.member.journey.newGoal')} placeholder={t('public.member.journey.newGoal')} className={inputClasses} value={goal} onChange={(e) => setGoal(e.target.value)} /><Button type="submit" variant="secondary" disabled={busy} aria-label={t('public.member.journey.addGoal')}><i className="ri-add-line" /></Button></form><div className="mt-3 space-y-2">{journey.goals.map((item) => <label key={item.id} className="flex items-center gap-3 rounded-xl bg-surface p-3 text-sm"><input type="checkbox" checked={item.status === 'Completed'} onChange={() => void communityApi.updateGoal(item.id, item.status === 'Completed' ? 'Open' : 'Completed').then(load)} className="accent-green" /><span className={item.status === 'Completed' ? 'line-through opacity-60' : ''}>{item.title}</span></label>)}</div></div><form onSubmit={checkIn} className="space-y-3"><textarea required minLength={10} rows={4} aria-label={t('public.member.journey.checkIn')} placeholder={t('public.member.journey.checkIn')} className={inputClasses} value={summary} onChange={(e) => setSummary(e.target.value)} /><div className="flex items-center justify-between gap-3"><select aria-label={t('public.member.journey.rating')} value={rating} onChange={(e) => setRating(Number(e.target.value))} className={`${inputClasses} max-w-32`}><option value="5">5 / 5</option><option value="4">4 / 5</option><option value="3">3 / 5</option><option value="2">2 / 5</option><option value="1">1 / 5</option></select><label className="flex items-center gap-2 text-xs text-ink-variant"><input type="checkbox" checked={support} onChange={(e) => setSupport(e.target.checked)} /> {t('public.member.journey.support')}</label></div><Button type="submit" variant="tertiary" disabled={busy}>{t('public.member.journey.submit')}</Button></form></div></section>;
}
