import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, PageHeader } from '../../../components/ui';
import { communityMarketplaceApi } from '../../../lib/api/community-marketplace';
import type { AdvertisingCampaign, CommunityOrganizer } from '../../../lib/api/types';

const tone: Record<string, string> = { Approved: 'bg-green/10 text-green border-green/20', Pending: 'bg-gold/10 text-gold-ink border-gold/30', Submitted: 'bg-gold/10 text-gold-ink border-gold/30', Rejected: 'bg-red/5 text-red-link border-red/25', Suspended: 'bg-red/5 text-red-link border-red/25', Paused: 'bg-line text-ink-variant border-line' };

export default function MarketplaceAdminPage() {
  const { i18n } = useTranslation(); const fr = i18n.language.startsWith('fr');
  const [organizers, setOrganizers] = useState<CommunityOrganizer[]>([]); const [ads, setAds] = useState<AdvertisingCampaign[]>([]); const [tab, setTab] = useState<'organizers' | 'ads'>('organizers'); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { const [organizerResponse, adResponse] = await Promise.all([communityMarketplaceApi.getAdminOrganizers(), communityMarketplaceApi.getAdminAds()]); if (organizerResponse.data) setOrganizers(organizerResponse.data); if (adResponse.data) setAds(adResponse.data); };
  useEffect(() => { void load(); }, []);
  const run = async (operation: () => Promise<{ success: boolean; message?: string }>) => { setBusy(true); try { const response = await operation(); setNotice(response.success ? (fr ? 'Décision enregistrée.' : 'Decision saved.') : response.message || 'Error'); await load(); } finally { setBusy(false); } };
  return <div><PageHeader variant="admin" eyebrow={fr ? 'Économie communautaire' : 'Community economy'} title={fr ? 'Organisateurs et publicité' : 'Organizers and advertising'} description={fr ? 'Validez les vendeurs, supervisez les paiements et contrôlez chaque placement publicitaire.' : 'Review sellers, oversee payments, and control every advertising placement.'} />
    <div className="mt-7 flex gap-2 rounded-xl border border-line bg-surface p-1.5"><button type="button" onClick={() => setTab('organizers')} className={`min-h-11 flex-1 rounded-lg text-[10px] font-bold uppercase tracking-wider ${tab === 'organizers' ? 'bg-green text-white' : 'text-green'}`}>{fr ? 'Organisateurs' : 'Organizers'} · {organizers.length}</button><button type="button" onClick={() => setTab('ads')} className={`min-h-11 flex-1 rounded-lg text-[10px] font-bold uppercase tracking-wider ${tab === 'ads' ? 'bg-green text-white' : 'text-green'}`}>{fr ? 'Publicités' : 'Advertising'} · {ads.length}</button></div>
    {notice && <p className="mt-4 border-l-2 border-green bg-green/5 px-4 py-3 text-sm text-green">{notice}</p>}
    {tab === 'organizers' ? <div className="mt-6 grid gap-5 xl:grid-cols-2">{organizers.map((item) => <article key={item.id} className="rounded-[22px] border border-line bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.15em] text-red-link">{item.contactEmail}</p><h2 className="mt-2 font-display text-2xl font-bold text-green-deep">{item.displayName}</h2></div><span className={`rounded-full border px-3 py-1 text-[9px] font-bold uppercase ${tone[item.status] || tone.Paused}`}>{item.status}</span></div><p className="mt-4 text-sm leading-6 text-ink-variant">{item.description || (fr ? 'Aucune présentation.' : 'No description.')}</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-[9px] font-bold uppercase"><span className={`rounded-lg p-3 ${item.stripeDetailsSubmitted ? 'bg-green/10 text-green' : 'bg-canvas text-ink-variant'}`}>{fr ? 'Identité' : 'Identity'}</span><span className={`rounded-lg p-3 ${item.stripeChargesEnabled ? 'bg-green/10 text-green' : 'bg-canvas text-ink-variant'}`}>{fr ? 'Paiements' : 'Charges'}</span><span className={`rounded-lg p-3 ${item.stripePayoutsEnabled ? 'bg-green/10 text-green' : 'bg-canvas text-ink-variant'}`}>{fr ? 'Versements' : 'Payouts'}</span></div><div className="mt-5 flex flex-wrap gap-2 border-t border-line pt-5"><Button type="button" disabled={busy || item.status === 'Approved'} onClick={() => void run(() => communityMarketplaceApi.reviewOrganizer(item.id, 'Approved'))}>{fr ? 'Approuver' : 'Approve'}</Button><Button type="button" variant="destructive" disabled={busy || item.status === 'Rejected'} onClick={() => void run(() => communityMarketplaceApi.reviewOrganizer(item.id, 'Rejected', fr ? 'Profil non conforme aux critères HCBE.' : 'Profile does not meet HCBE criteria.'))}>{fr ? 'Refuser' : 'Reject'}</Button>{item.status === 'Approved' && <Button type="button" variant="secondary" disabled={busy} onClick={() => void run(() => communityMarketplaceApi.reviewOrganizer(item.id, 'Suspended'))}>{fr ? 'Suspendre' : 'Suspend'}</Button>}</div></article>)}</div> :
      <div className="mt-6 grid gap-5 xl:grid-cols-2">{ads.map((item) => <article key={item.id} className="overflow-hidden rounded-[22px] border border-line bg-surface">{item.imageUrl && <img src={item.imageUrl} alt="" className="h-44 w-full object-cover" />}<div className="p-6"><div className="flex justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.15em] text-red-link">{item.advertiserName}</p><h2 className="mt-2 font-display text-2xl font-bold text-green-deep">{item.title}</h2></div><span className={`h-fit rounded-full border px-3 py-1 text-[9px] font-bold uppercase ${tone[item.status] || tone.Paused}`}>{item.status}</span></div><p className="mt-3 text-sm leading-6 text-ink-variant">{item.body}</p><dl className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="bg-canvas p-3"><dt className="text-[8px] uppercase text-ink-variant">{fr ? 'Vues' : 'Views'}</dt><dd className="mt-1 font-bold text-green">{item.impressionCount}</dd></div><div className="bg-canvas p-3"><dt className="text-[8px] uppercase text-ink-variant">{fr ? 'Clics' : 'Clicks'}</dt><dd className="mt-1 font-bold text-green">{item.clickCount}</dd></div><div className="bg-canvas p-3"><dt className="text-[8px] uppercase text-ink-variant">CTR</dt><dd className="mt-1 font-bold text-green">{item.impressionCount ? ((item.clickCount / item.impressionCount) * 100).toFixed(1) : '0'}%</dd></div></dl><div className="mt-5 flex gap-2 border-t border-line pt-5"><Button type="button" disabled={busy || item.status === 'Approved'} onClick={() => void run(() => communityMarketplaceApi.reviewAd(item.id, 'Approved'))}>{fr ? 'Publier' : 'Publish'}</Button><Button type="button" variant="destructive" disabled={busy || item.status === 'Rejected'} onClick={() => void run(() => communityMarketplaceApi.reviewAd(item.id, 'Rejected'))}>{fr ? 'Refuser' : 'Reject'}</Button>{item.status === 'Approved' && <Button type="button" variant="secondary" disabled={busy} onClick={() => void run(() => communityMarketplaceApi.reviewAd(item.id, 'Paused'))}>{fr ? 'Suspendre' : 'Pause'}</Button>}</div></div></article>)}</div>}
  </div>;
}
