import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AdminPageHeader } from '../../../components/admin/AdminPageHeader';
import { apiClient } from '../../../lib/api/client';
import { financeApi, type CampaignInput, type MembershipPlanInput } from '../../../lib/api/finance';
import type { AdminMembership, DonationCampaign, FinanceDashboard, FinancialTransaction, MembershipPlan } from '../../../lib/api/types';

type Tab = 'overview' | 'memberships' | 'transactions' | 'plans' | 'campaigns';
const emptyPlan: MembershipPlanInput = { name: '', nameEn: '', description: '', descriptionEn: '', amountCents: 2500, currency: 'cad', billingMode: 'Annual', benefits: [], isActive: true, displayOrder: 0, stripePriceId: '' };
const emptyCampaign: CampaignInput = { slug: '', title: '', titleEn: '', description: '', descriptionEn: '', goalAmountCents: 100000, currency: 'cad', imageUrl: '', allowRecurring: true, isPublished: false, startsAtUtc: undefined, endsAtUtc: undefined };
const field = 'w-full rounded-xl border border-line bg-white px-3 py-2.5 text-sm text-ink outline-none transition focus:border-green';
const money = (value: number, locale = 'fr-CA') => new Intl.NumberFormat(locale, { style: 'currency', currency: 'CAD' }).format(value / 100);
const toLocalDateTime = (value?: string) => {
  if (!value) return '';
  const date = new Date(value);
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000);
  return local.toISOString().slice(0, 16);
};
const toUtcDateTime = (value?: string) => value ? new Date(value).toISOString() : undefined;

export default function AdminFinancePage() {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en'); const locale = fr ? 'fr-CA' : 'en-CA';
  const [tab, setTab] = useState<Tab>('overview'); const [dashboard, setDashboard] = useState<FinanceDashboard | null>(null);
  const [transactions, setTransactions] = useState<FinancialTransaction[]>([]); const [memberships, setMemberships] = useState<AdminMembership[]>([]); const [plans, setPlans] = useState<MembershipPlan[]>([]); const [campaigns, setCampaigns] = useState<DonationCampaign[]>([]);
  const [status, setStatus] = useState(''); const [kind, setKind] = useState(''); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [refundTarget, setRefundTarget] = useState<FinancialTransaction | null>(null);
  const query = useMemo(() => { const params = new URLSearchParams(); if (status) params.set('status', status); if (kind) params.set('kind', kind); if (search) params.set('search', search); const value = params.toString(); return value ? `?${value}` : ''; }, [status, kind, search]);
  const load = async () => { const [d, m, t, p, c] = await Promise.all([financeApi.adminDashboard(), financeApi.adminMemberships(search), financeApi.adminTransactions(query), financeApi.adminPlans(), financeApi.adminCampaigns()]); if (d.data) setDashboard(d.data); if (m.data) setMemberships(m.data); if (t.data) setTransactions(t.data); if (p.data) setPlans(p.data); if (c.data) setCampaigns(c.data); };
  useEffect(() => { void load().catch((reason) => setNotice(reason instanceof Error ? reason.message : 'Erreur')); }, [query]);
  const run = async (work: () => Promise<unknown>, message: string) => { setBusy(true); setNotice(''); try { const response = await work() as { message?: string }; setNotice(response?.message || message); await load(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Erreur'); } finally { setBusy(false); } };
  const exportCsv = async () => { const result = await apiClient.download(`/api/admin/finance/transactions/export${query}`); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.fileName || 'hcbe-finance.csv'; link.click(); URL.revokeObjectURL(url); };

  const cards = dashboard ? [
    [fr ? 'Revenus nets' : 'Net revenue', dashboard.paidAmountCents - dashboard.refundedAmountCents, 'ri-funds-line'],
    [fr ? 'Adhésions' : 'Memberships', dashboard.membershipRevenueCents, 'ri-bank-card-line'],
    [fr ? 'Contributions' : 'Contributions', dashboard.donationRevenueCents, 'ri-hand-heart-line'],
  ] as const : [];

  return <div className="space-y-6" data-testid="admin-finance-page"><AdminPageHeader title={fr ? 'Finances et adhésions' : 'Finance and memberships'} subtitle={fr ? 'Pilotez les cotisations, contributions, remboursements et campagnes depuis un registre unique.' : 'Manage dues, contributions, refunds and campaigns from one ledger.'} icon="ri-secure-payment-line" count={dashboard?.paidTransactionCount} />
    <nav className="flex gap-2 overflow-x-auto rounded-2xl border border-line bg-surface p-2">{([['overview', 'Vue d’ensemble', 'Overview'], ['memberships', 'Adhésions', 'Memberships'], ['transactions', 'Transactions', 'Transactions'], ['plans', 'Formules', 'Plans'], ['campaigns', 'Campagnes', 'Campaigns']] as const).map(([value, labelFr, labelEn]) => <button key={value} onClick={() => setTab(value)} className={`min-w-max rounded-xl px-4 py-3 text-[10px] font-bold uppercase tracking-[.12em] transition ${tab === value ? 'bg-green text-white shadow-md' : 'text-ink-variant hover:bg-green/5'}`}>{fr ? labelFr : labelEn}</button>)}</nav>
    {notice && <div className="rounded-xl border border-gold/30 bg-gold/10 p-4 text-sm text-green-deep">{notice}</div>}

    {tab === 'overview' && <div className="space-y-6">{!dashboard ? <div className="h-44 animate-pulse rounded-3xl bg-surface" /> : <><section className="grid gap-4 md:grid-cols-3">{cards.map(([label, value, icon]) => <article key={label} className="relative overflow-hidden rounded-[24px] border border-line bg-surface p-6 shadow-[0_15px_38px_rgba(0,59,27,.06)]"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-green/8 text-xl text-green"><i className={icon} /></span><p className="mt-6 text-[9px] font-bold uppercase tracking-[.16em] text-ink-variant">{label}</p><strong className="mt-2 block font-display text-4xl text-green-deep">{money(value, locale)}</strong></article>)}</section><section className="grid gap-4 md:grid-cols-3"><Metric label={fr ? 'Membres en règle' : 'Active members'} value={dashboard.activeMembers} /><Metric label={fr ? 'Échéance sous 30 jours' : 'Expiring in 30 days'} value={dashboard.expiringMembers} /><Metric label={fr ? 'Remboursements' : 'Refunds'} value={money(dashboard.refundedAmountCents, locale)} /></section><TransactionTable items={dashboard.recentTransactions} locale={locale} fr={fr} onRefund={setRefundTarget} /></>}</div>}

    {tab === 'memberships' && <section className="overflow-hidden rounded-[24px] border border-line bg-surface"><header className="border-b border-line bg-green/[.03] p-5"><input className={field} placeholder={fr ? 'Rechercher un membre par nom ou courriel…' : 'Search a member by name or email…'} value={search} onChange={(event) => setSearch(event.target.value)} /></header><div className="divide-y divide-line">{memberships.length === 0 ? <p className="p-8 text-center text-sm text-ink-variant">{fr ? 'Aucun membre trouvé.' : 'No member found.'}</p> : memberships.map((item) => <MembershipRow key={item.userId} item={item} busy={busy} locale={locale} fr={fr} onSave={(statusValue, endDate) => run(() => financeApi.updateStanding(item.userId, statusValue, endDate || undefined, 'Updated by finance administrator'), fr ? 'Adhésion enregistrée.' : 'Membership saved.')} />)}</div></section>}

    {tab === 'transactions' && <section className="overflow-hidden rounded-[24px] border border-line bg-surface"><header className="grid gap-3 border-b border-line bg-green/[.03] p-5 lg:grid-cols-[1fr_180px_180px_auto]"><input className={field} placeholder={fr ? 'Nom, courriel ou reçu…' : 'Name, email or receipt…'} value={search} onChange={(event) => setSearch(event.target.value)} /><select className={field} value={kind} onChange={(event) => setKind(event.target.value)}><option value="">{fr ? 'Tous les types' : 'All types'}</option><option value="Membership">{fr ? 'Adhésion' : 'Membership'}</option><option value="Donation">{fr ? 'Contribution' : 'Contribution'}</option></select><select className={field} value={status} onChange={(event) => setStatus(event.target.value)}><option value="">{fr ? 'Tous les statuts' : 'All statuses'}</option>{['Pending', 'Paid', 'Failed', 'PartiallyRefunded', 'Refunded', 'Disputed'].map((value) => <option key={value}>{value}</option>)}</select><button onClick={() => void exportCsv()} className="rounded-xl border border-green px-4 text-[10px] font-bold uppercase tracking-[.12em] text-green"><i className="ri-download-line mr-2" />CSV</button></header><TransactionTable items={transactions} locale={locale} fr={fr} onRefund={setRefundTarget} /></section>}

    {tab === 'plans' && <section className="space-y-5"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-red-link">{fr ? 'Catalogue' : 'Catalog'}</p><h2 className="font-display text-3xl font-bold text-green-deep">{fr ? 'Formules d’adhésion' : 'Membership plans'}</h2></div><div className="grid gap-5 xl:grid-cols-2">{plans.map((plan) => <PlanEditor key={plan.id} initial={{ ...plan, benefits: plan.benefits }} busy={busy} label={fr ? 'Modifier la formule' : 'Edit plan'} onSave={(value) => run(() => financeApi.updatePlan(plan.id, value), fr ? 'Formule enregistrée.' : 'Plan saved.')} />)}<PlanEditor initial={emptyPlan} busy={busy} label={fr ? 'Nouvelle formule' : 'New plan'} onSave={(value) => run(() => financeApi.createPlan(value), fr ? 'Formule créée.' : 'Plan created.')} /></div></section>}

    {tab === 'campaigns' && <section className="space-y-5"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-red-link">{fr ? 'Mobilisation' : 'Mobilization'}</p><h2 className="font-display text-3xl font-bold text-green-deep">{fr ? 'Campagnes de contribution' : 'Contribution campaigns'}</h2></div><div className="grid gap-5 xl:grid-cols-2">{campaigns.map((campaign) => <CampaignEditor key={campaign.id} initial={campaign} busy={busy} label={`${campaign.title} · ${money(campaign.raisedAmountCents, locale)}`} onSave={(value) => run(() => financeApi.updateCampaign(campaign.id, value), fr ? 'Campagne enregistrée.' : 'Campaign saved.')} />)}<CampaignEditor initial={emptyCampaign} busy={busy} label={fr ? 'Nouvelle campagne' : 'New campaign'} onSave={(value) => run(() => financeApi.createCampaign(value), fr ? 'Campagne créée.' : 'Campaign created.')} /></div></section>}
    {refundTarget && <RefundDialog transaction={refundTarget} locale={locale} fr={fr} busy={busy} onClose={() => setRefundTarget(null)} onConfirm={async (amountCents, reason) => { await run(() => financeApi.refund(refundTarget.id, amountCents, reason), fr ? 'Remboursement demandé.' : 'Refund requested.'); setRefundTarget(null); }} />}
  </div>;
}

function MembershipRow({ item, busy, locale, fr, onSave }: { item: AdminMembership; busy: boolean; locale: string; fr: boolean; onSave: (status: string, endDate: string) => void }) {
  const [status, setStatus] = useState(item.status);
  const [endDate, setEndDate] = useState(item.currentPeriodEndUtc?.slice(0, 10) || '');
  useEffect(() => { setStatus(item.status); setEndDate(item.currentPeriodEndUtc?.slice(0, 10) || ''); }, [item]);
  return <article className="grid items-center gap-4 p-5 lg:grid-cols-[1.3fr_.8fr_180px_180px_auto]">
    <div><strong className="block font-display text-lg text-green-deep">{item.memberName || '—'}</strong><span className="text-xs text-ink-variant">{item.email}</span></div>
    <div><span className="block text-[9px] font-bold uppercase tracking-[.13em] text-ink-variant">{fr ? 'Formule' : 'Plan'}</span><span className="mt-1 block text-sm">{item.planName || (fr ? 'Aucune' : 'None')}</span>{item.autoRenew && <span className="text-[10px] text-green">{fr ? 'Renouvellement automatique' : 'Auto-renewal'}</span>}</div>
    <label className="text-[9px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Statut' : 'Status'}<select className={`${field} mt-1`} value={status} onChange={(event) => setStatus(event.target.value as AdminMembership['status'])}>{['Inactive', 'Active', 'GracePeriod', 'Expired'].map((value) => <option key={value}>{value}</option>)}</select></label>
    <label className="text-[9px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Valide jusqu’au' : 'Valid until'}<input type="date" className={`${field} mt-1`} value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label>
    <button disabled={busy} onClick={() => onSave(status, endDate ? new Date(`${endDate}T23:59:59Z`).toISOString() : '')} className="rounded-xl border border-green px-4 py-3 text-[9px] font-bold uppercase tracking-[.12em] text-green transition hover:bg-green hover:text-white disabled:opacity-50">{fr ? 'Enregistrer' : 'Save'}</button>
  </article>;
}

function RefundDialog({ transaction, locale, fr, busy, onClose, onConfirm }: {
  transaction: FinancialTransaction;
  locale: string;
  fr: boolean;
  busy: boolean;
  onClose: () => void;
  onConfirm: (amountCents: number, reason: string) => Promise<void>;
}) {
  const remaining = transaction.amountCents - transaction.refundedAmountCents;
  const [amount, setAmount] = useState((remaining / 100).toFixed(2));
  const [reason, setReason] = useState('');
  const amountCents = Math.round(Number(amount) * 100);
  const valid = Number.isFinite(amountCents) && amountCents > 0 && amountCents <= remaining && reason.trim().length >= 3;

  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-green-deep/70 p-4 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <form className="w-full max-w-lg overflow-hidden rounded-[28px] border border-white/20 bg-surface shadow-[0_30px_100px_rgba(0,0,0,.3)]" role="dialog" aria-modal="true" aria-labelledby="refund-title" onSubmit={(event) => { event.preventDefault(); if (valid) void onConfirm(amountCents, reason.trim()); }}>
      <header className="relative overflow-hidden bg-green-deep p-7 text-white"><div className="absolute -right-12 -top-16 h-40 w-40 rounded-full border-[28px] border-gold/10" /><p className="text-[9px] font-bold uppercase tracking-[.2em] text-gold">{fr ? 'Contrôle financier' : 'Financial control'}</p><h2 id="refund-title" className="mt-2 font-display text-3xl font-bold text-white">{fr ? 'Rembourser un paiement' : 'Refund a payment'}</h2><p className="mt-2 text-sm text-green-dim">{transaction.receiptNumber} · {transaction.payerEmail}</p></header>
      <div className="space-y-5 p-7"><div className="grid grid-cols-2 gap-3 rounded-2xl border border-line bg-canvas p-4 text-sm"><span className="text-ink-variant">{fr ? 'Montant disponible' : 'Available amount'}</span><strong className="text-right text-green-deep">{money(remaining, locale)}</strong></div><label className="block text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Montant à rembourser (CAD)' : 'Refund amount (CAD)'}<input autoFocus required type="number" min="0.01" max={(remaining / 100).toFixed(2)} step="0.01" className={`${field} mt-2`} value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="block text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Motif interne' : 'Internal reason'}<textarea required minLength={3} maxLength={300} rows={3} className={`${field} mt-2 resize-none`} value={reason} onChange={(event) => setReason(event.target.value)} placeholder={fr ? 'Ex. demande du membre' : 'E.g. member request'} /></label><p className="rounded-xl border border-gold/25 bg-gold/8 p-3 text-xs leading-5 text-ink-variant"><i className="ri-information-line mr-2 text-gold-ink" />{fr ? 'Un remboursement complet de la dernière cotisation désactive aussi l’adhésion et annule son renouvellement automatique.' : 'A full refund of the latest membership payment also deactivates the membership and cancels automatic renewal.'}</p><div className="flex justify-end gap-3 border-t border-line pt-5"><button type="button" onClick={onClose} disabled={busy} className="rounded-xl border border-line px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Annuler' : 'Cancel'}</button><button disabled={!valid || busy} className="rounded-xl bg-red-link px-5 py-3 text-[10px] font-bold uppercase tracking-[.12em] text-white disabled:opacity-50">{busy ? (fr ? 'Traitement…' : 'Processing…') : (fr ? 'Confirmer le remboursement' : 'Confirm refund')}</button></div></div>
    </form>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <article className="rounded-2xl border border-line bg-surface p-5"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-ink-variant">{label}</p><strong className="mt-2 block font-display text-2xl text-green-deep">{value}</strong></article>; }
function TransactionTable({ items, locale, fr, onRefund }: { items: FinancialTransaction[]; locale: string; fr: boolean; onRefund: (item: FinancialTransaction) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-line bg-canvas/60 text-[9px] uppercase tracking-[.14em] text-ink-variant"><th className="p-4">{fr ? 'Payeur' : 'Payer'}</th><th>{fr ? 'Type' : 'Type'}</th><th>{fr ? 'Montant' : 'Amount'}</th><th>{fr ? 'Statut' : 'Status'}</th><th>{fr ? 'Date' : 'Date'}</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={6} className="p-8 text-center text-sm text-ink-variant">{fr ? 'Aucune transaction.' : 'No transactions.'}</td></tr> : items.map((item) => <tr key={item.id} className="border-b border-line/70 text-sm"><td className="p-4"><strong className="block text-green-deep">{item.isAnonymous ? (fr ? 'Anonyme' : 'Anonymous') : item.payerName || '—'}</strong><span className="text-xs text-ink-variant">{item.payerEmail}</span></td><td>{item.kind}</td><td className="font-bold text-green-deep">{money(item.amountCents - item.refundedAmountCents, locale)}</td><td><span className="rounded-full bg-green/8 px-2.5 py-1 text-[9px] font-bold uppercase text-green">{item.status}</span></td><td>{new Date(item.createdAtUtc).toLocaleDateString(locale)}</td><td className="p-4 text-right">{item.receiptUrl && <a className="mr-3 text-green" href={item.receiptUrl} download title={fr ? 'Télécharger le reçu PDF' : 'Download PDF receipt'} aria-label={fr ? 'Télécharger le reçu PDF' : 'Download PDF receipt'}><i className="ri-file-pdf-2-line" /></a>}{(item.status === 'Paid' || item.status === 'PartiallyRefunded') && <button onClick={() => onRefund(item)} className="text-red-link" title="Refund"><i className="ri-arrow-go-back-line" /></button>}</td></tr>)}</tbody></table></div>; }

function PlanEditor({ initial, busy, label, onSave }: { initial: MembershipPlanInput; busy: boolean; label: string; onSave: (value: MembershipPlanInput) => void }) { const [value, setValue] = useState(initial); const [benefits, setBenefits] = useState(initial.benefits.join('\n')); return <form onSubmit={(event) => { event.preventDefault(); onSave({ ...value, amountCents: Number(value.amountCents), displayOrder: Number(value.displayOrder), benefits: benefits.split('\n').map((item) => item.trim()).filter(Boolean) }); }} className="rounded-[24px] border border-line bg-surface p-6 shadow-[0_12px_35px_rgba(0,59,27,.05)]"><h3 className="font-display text-xl font-bold text-green-deep">{label}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required className={field} placeholder="Nom (FR)" value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} /><input className={field} placeholder="Name (EN)" value={value.nameEn || ''} onChange={(e) => setValue({ ...value, nameEn: e.target.value })} /><textarea required rows={3} className={field} placeholder="Description (FR)" value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} /><textarea rows={3} className={field} placeholder="Description (EN)" value={value.descriptionEn || ''} onChange={(e) => setValue({ ...value, descriptionEn: e.target.value })} /><label className="text-xs text-ink-variant">Montant (cents)<input required type="number" min="100" className={`${field} mt-1`} value={value.amountCents} onChange={(e) => setValue({ ...value, amountCents: Number(e.target.value) })} /></label><label className="text-xs text-ink-variant">Facturation<select className={`${field} mt-1`} value={value.billingMode} onChange={(e) => setValue({ ...value, billingMode: e.target.value as 'Annual' | 'Recurring' })}><option value="Annual">Annual</option><option value="Recurring">Recurring</option></select></label><textarea rows={4} className={`${field} sm:col-span-2`} placeholder="Avantages — un par ligne" value={benefits} onChange={(e) => setBenefits(e.target.value)} /><input className={field} placeholder="Stripe Price ID (optionnel)" value={value.stripePriceId || ''} onChange={(e) => setValue({ ...value, stripePriceId: e.target.value })} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.isActive} onChange={(e) => setValue({ ...value, isActive: e.target.checked })} /> Active</label></div><button disabled={busy} className="mt-5 rounded-xl bg-green px-5 py-3 text-[10px] font-bold uppercase tracking-[.13em] text-white">Enregistrer</button></form>; }

function CampaignEditor({ initial, busy, label, onSave }: { initial: CampaignInput | DonationCampaign; busy: boolean; label: string; onSave: (value: CampaignInput) => void }) {
  const [value, setValue] = useState<CampaignInput>({ slug: initial.slug, title: initial.title, titleEn: initial.titleEn, description: initial.description, descriptionEn: initial.descriptionEn, goalAmountCents: initial.goalAmountCents, currency: initial.currency, imageUrl: initial.imageUrl, allowRecurring: initial.allowRecurring, isPublished: initial.isPublished, startsAtUtc: toLocalDateTime(initial.startsAtUtc), endsAtUtc: toLocalDateTime(initial.endsAtUtc) });
  return <form onSubmit={(event) => { event.preventDefault(); onSave({ ...value, goalAmountCents: Number(value.goalAmountCents), startsAtUtc: toUtcDateTime(value.startsAtUtc), endsAtUtc: toUtcDateTime(value.endsAtUtc) }); }} className="rounded-[24px] border border-line bg-surface p-6 shadow-[0_12px_35px_rgba(0,59,27,.05)]"><h3 className="font-display text-xl font-bold text-green-deep">{label}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required className={field} placeholder="identifiant-campagne" value={value.slug} onChange={(e) => setValue({ ...value, slug: e.target.value })} /><input required className={field} placeholder="Titre (FR)" value={value.title} onChange={(e) => setValue({ ...value, title: e.target.value })} /><input className={field} placeholder="Title (EN)" value={value.titleEn || ''} onChange={(e) => setValue({ ...value, titleEn: e.target.value })} /><label className="text-xs text-ink-variant">Objectif (cents)<input type="number" min="0" className={`${field} mt-1`} value={value.goalAmountCents} onChange={(e) => setValue({ ...value, goalAmountCents: Number(e.target.value) })} /></label><textarea required rows={4} className={`${field} sm:col-span-2`} placeholder="Description (FR)" value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} /><textarea rows={3} className={`${field} sm:col-span-2`} placeholder="Description (EN)" value={value.descriptionEn || ''} onChange={(e) => setValue({ ...value, descriptionEn: e.target.value })} /><label className="text-xs text-ink-variant">Début de publication<input type="datetime-local" className={`${field} mt-1`} value={value.startsAtUtc || ''} onChange={(e) => setValue({ ...value, startsAtUtc: e.target.value || undefined })} /></label><label className="text-xs text-ink-variant">Fin de publication<input type="datetime-local" className={`${field} mt-1`} value={value.endsAtUtc || ''} onChange={(e) => setValue({ ...value, endsAtUtc: e.target.value || undefined })} /></label><label className="text-xs text-ink-variant sm:col-span-2">Image de campagne (URL HTTPS)<input type="url" className={`${field} mt-1`} placeholder="https://…" value={value.imageUrl || ''} onChange={(e) => setValue({ ...value, imageUrl: e.target.value })} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.allowRecurring} onChange={(e) => setValue({ ...value, allowRecurring: e.target.checked })} /> Récurrence autorisée</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.isPublished} onChange={(e) => setValue({ ...value, isPublished: e.target.checked })} /> Publiée</label></div><button disabled={busy} className="mt-5 rounded-xl bg-green px-5 py-3 text-[10px] font-bold uppercase tracking-[.13em] text-white">Enregistrer</button></form>;
}
