import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useSearchParams } from 'react-router-dom';
import Navbar from '../../components/feature/Navbar';
import Footer from '../../components/feature/Footer';
import { useAuth } from '../../contexts/AuthContext';
import { financeApi } from '../../lib/api/finance';
import type { DonationCampaign } from '../../lib/api/types';

const presets = [2500, 5000, 10000, 25000];

export default function ContributionPage() {
  const { i18n } = useTranslation(); const fr = !i18n.language.startsWith('en'); const { user } = useAuth();
  const [searchParams] = useSearchParams();
  const [campaigns, setCampaigns] = useState<DonationCampaign[]>([]); const [campaignId, setCampaignId] = useState('');
  const [amount, setAmount] = useState(5000); const [custom, setCustom] = useState(''); const [email, setEmail] = useState(user?.email || '');
  const [name, setName] = useState(`${user?.firstName || ''} ${user?.lastName || ''}`.trim()); const [recurring, setRecurring] = useState(false);
  const [anonymous, setAnonymous] = useState(false); const [recognition, setRecognition] = useState(false); const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { financeApi.getCampaigns().then((response) => { if (response.data) { setCampaigns(response.data); if (response.data[0]) setCampaignId(response.data[0].id); } }).catch(() => undefined); }, []);
  const selected = campaigns.find((item) => item.id === campaignId); const amountCents = custom ? Math.round(Number(custom) * 100) : amount;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await financeApi.createDonationCheckout({ campaignId: campaignId || undefined, amountCents, currency: 'cad', email, name: name || undefined, isAnonymous: anonymous, allowPublicRecognition: !anonymous && recognition, message: message || undefined, isRecurring: recurring }); if (!response.data?.checkoutUrl) throw new Error(response.message || 'Checkout unavailable'); window.location.assign(response.data.checkoutUrl); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Checkout unavailable'); setBusy(false); } };
  const money = (cents: number) => new Intl.NumberFormat(fr ? 'fr-CA' : 'en-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(cents / 100);

  return <div className="min-h-screen bg-canvas"><Navbar /><main>
    <section className="relative isolate overflow-hidden bg-green-deep px-5 py-20 text-white sm:py-28"><div className="absolute inset-0 -z-10 opacity-45 [background-image:linear-gradient(rgba(255,255,255,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.04)_1px,transparent_1px)] [background-size:54px_54px]" /><div className="absolute -right-32 -top-40 -z-10 h-[520px] w-[520px] rounded-full border-[86px] border-gold/[.08]" /><div className="container-page"><p className="text-[10px] font-bold uppercase tracking-[.24em] text-gold">{fr ? 'Solidarité en action' : 'Solidarity in action'}</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-bold leading-[.98] text-white sm:text-7xl">{fr ? 'Chaque contribution rapproche notre communauté.' : 'Every contribution brings our community closer.'}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-green-dim">{fr ? 'Soutenez les services, les projets et les initiatives qui accompagnent les Burkinabè partout au Canada.' : 'Support the services, projects and initiatives serving Burkinabè communities across Canada.'}</p></div></section>
    <section className="container-page relative z-10 -mt-10 pb-20">{searchParams.get('payment') === 'cancelled' && <div role="status" className="mb-5 rounded-2xl border border-gold/40 bg-[#fff8dc] p-4 text-sm text-green-deep"><i className="ri-information-line mr-2 text-gold-ink" />{fr ? 'Le paiement a été annulé. Aucun montant n’a été débité; vous pouvez reprendre lorsque vous le souhaitez.' : 'Payment was cancelled. Nothing was charged; you can resume whenever you are ready.'}</div>}<div className="grid overflow-hidden rounded-[30px] border border-line bg-surface shadow-[0_28px_80px_rgba(0,45,22,.14)] lg:grid-cols-[.9fr_1.1fr]">
      <aside className="relative overflow-hidden bg-[#edf1e9] p-7 sm:p-10"><p className="text-[9px] font-bold uppercase tracking-[.2em] text-red-link">{fr ? 'Choisir une initiative' : 'Choose an initiative'}</p><div className="mt-5 space-y-3">{campaigns.length === 0 ? <button className="w-full rounded-2xl border border-green bg-green p-5 text-left text-white"><strong className="font-display text-xl">{fr ? 'Fonds communautaire HCBE' : 'HCBE Community Fund'}</strong><span className="mt-2 block text-xs text-white/70">{fr ? 'Soutien général aux activités et services.' : 'General support for activities and services.'}</span></button> : campaigns.map((campaign) => <button key={campaign.id} type="button" onClick={() => { setCampaignId(campaign.id); if (!campaign.allowRecurring) setRecurring(false); }} className={`w-full overflow-hidden rounded-2xl border text-left transition ${campaignId === campaign.id ? 'border-green bg-green text-white shadow-lg' : 'border-line bg-white hover:border-green/30'}`}>{campaign.imageUrl && <img src={campaign.imageUrl} alt="" className="h-28 w-full object-cover" loading="lazy" />}<span className="block p-5"><strong className={`font-display text-xl ${campaignId === campaign.id ? 'text-white' : 'text-green-deep'}`}>{fr ? campaign.title : campaign.titleEn || campaign.title}</strong><span className={`mt-2 line-clamp-2 block text-xs leading-5 ${campaignId === campaign.id ? 'text-white/70' : 'text-ink-variant'}`}>{fr ? campaign.description : campaign.descriptionEn || campaign.description}</span>{campaign.goalAmountCents > 0 && <span className="mt-4 block"><span className={`block h-1.5 overflow-hidden rounded-full ${campaignId === campaign.id ? 'bg-white/15' : 'bg-line'}`}><span className="block h-full bg-gold" style={{ width: `${Math.min(100, campaign.raisedAmountCents / campaign.goalAmountCents * 100)}%` }} /></span><span className="mt-2 flex justify-between text-[10px]"><span>{money(campaign.raisedAmountCents)}</span><span>{campaign.supporterCount} {fr ? 'contributions' : 'contributions'}</span></span></span>}</span></button>)}</div><div className="mt-8 border-t border-green/10 pt-6"><div className="flex gap-3"><i className="ri-shield-check-line text-xl text-green" /><p className="text-xs leading-5 text-ink-variant">{fr ? 'Paiement sécurisé par Stripe. HCBE Canada ne reçoit ni ne conserve vos informations de carte.' : 'Secure payment by Stripe. HCBE Canada never receives or stores your card information.'}</p></div></div></aside>
      <form onSubmit={submit} className="p-7 sm:p-10"><p className="text-[9px] font-bold uppercase tracking-[.2em] text-red-link">{fr ? 'Votre contribution' : 'Your contribution'}</p><h2 className="mt-2 font-display text-3xl font-bold text-green-deep">{fr ? 'Choisissez votre montant' : 'Choose your amount'}</h2><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{presets.map((value) => <button type="button" key={value} onClick={() => { setAmount(value); setCustom(''); }} className={`rounded-xl border px-3 py-4 font-display text-xl font-bold transition ${!custom && amount === value ? 'border-green bg-green text-white' : 'border-line hover:border-green/30'}`}>{money(value)}</button>)}</div><label className="mt-4 block"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Autre montant (CAD)' : 'Other amount (CAD)'}</span><div className="mt-2 flex items-center rounded-xl border border-line bg-white px-4 focus-within:border-green"><span className="font-display text-2xl text-green-deep">$</span><input type="number" min="5" max="100000" step="1" value={custom} onChange={(event) => setCustom(event.target.value)} className="w-full border-0 bg-transparent px-3 py-3 text-lg outline-none" placeholder="75" /></div></label>{(!selected || selected.allowRecurring) && <div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={() => setRecurring(false)} className={`rounded-xl border p-4 text-sm font-semibold ${!recurring ? 'border-green bg-green/5 text-green' : 'border-line'}`}>{fr ? 'Une seule fois' : 'One time'}</button><button type="button" onClick={() => setRecurring(true)} className={`rounded-xl border p-4 text-sm font-semibold ${recurring ? 'border-green bg-green/5 text-green' : 'border-line'}`}>{fr ? 'Chaque année' : 'Every year'}</button></div>}
        <div className="my-7 border-t border-line" /><div className="grid gap-4 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Nom' : 'Name'}<input className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-green" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Courriel' : 'Email'} *<input required type="email" className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-green" value={email} onChange={(event) => setEmail(event.target.value)} /></label></div><label className="mt-4 block text-[10px] font-bold uppercase tracking-[.12em] text-ink-variant">{fr ? 'Message (facultatif)' : 'Message (optional)'}<textarea maxLength={500} rows={3} className="mt-2 w-full rounded-xl border border-line px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-green" value={message} onChange={(event) => setMessage(event.target.value)} /></label><div className="mt-5 space-y-3"><label className="flex cursor-pointer items-center gap-3 text-sm text-ink-variant"><input type="checkbox" className="h-5 w-5 accent-green" checked={anonymous} onChange={(event) => { setAnonymous(event.target.checked); if (event.target.checked) setRecognition(false); }} />{fr ? 'Afficher ma contribution comme anonyme' : 'Show my contribution as anonymous'}</label><label className={`flex items-center gap-3 text-sm ${anonymous ? 'text-ink-variant/40' : 'cursor-pointer text-ink-variant'}`}><input disabled={anonymous} type="checkbox" className="h-5 w-5 accent-green" checked={recognition} onChange={(event) => setRecognition(event.target.checked)} />{fr ? 'J’accepte que mon nom soit reconnu publiquement' : 'I agree to public recognition of my name'}</label></div>{error && <p className="mt-5 rounded-xl border border-red-link/20 bg-red-link/5 p-3 text-sm text-red-link">{error}</p>}<button disabled={busy || !Number.isFinite(amountCents) || amountCents < 500} className="mt-7 flex w-full items-center justify-between rounded-xl bg-gold px-5 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-green-deep shadow-[0_12px_28px_rgba(245,197,24,.24)] transition hover:bg-green hover:text-white disabled:opacity-50"><span>{busy ? (fr ? 'Ouverture du paiement…' : 'Opening checkout…') : (fr ? 'Continuer vers le paiement sécurisé' : 'Continue to secure payment')}</span><span>{money(amountCents)} <i className="ri-arrow-right-up-line ml-2" /></span></button><p className="mt-4 text-center text-[11px] leading-5 text-ink-variant">{fr ? 'Un reçu de paiement vous sera envoyé. Ce reçu n’est pas un reçu fiscal.' : 'A payment receipt will be emailed to you. It is not a charitable tax receipt.'}</p></form>
    </div></section>
  </main><Footer /></div>;
}
