import { useEffect, useMemo, useState } from 'react';
import { AdminPageHeader } from '../../../components/admin/AdminPageHeader';
import { impactApi } from '../../../lib/api/impact';
import type { ImpactDashboard } from '../../../lib/api/types';

const colors = ['bg-green', 'bg-gold', 'bg-red-link', 'bg-green-muted'];
export default function ImpactPage() {
  const [data, setData] = useState<ImpactDashboard | null>(null); const [error, setError] = useState('');
  useEffect(() => { impactApi.get().then((response) => response.data ? setData(response.data) : setError(response.message ?? 'Erreur')).catch(() => setError('Impossible de charger les indicateurs.')); }, []);
  const max = useMemo(() => Math.max(1, ...(data?.periods.flatMap((item) => [item.newMembers, item.eventRegistrations, item.serviceRequests, item.opportunityApplications]) ?? [1])), [data]);
  return <div className="space-y-6"><AdminPageHeader title="Impact communautaire" subtitle="Mesurez l’adoption, la participation et la qualité des services du HCBE." icon="ri-line-chart-line" count={data?.metrics.length} />
    {error && <p className="rounded-xl border border-error/20 bg-error/5 p-4 text-error">{error}</p>}
    {!data ? <div className="h-48 animate-pulse rounded-2xl bg-surface" /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.metrics.map((metric) => <article key={metric.key} className="rounded-2xl border border-line bg-surface p-5 shadow-[0_12px_32px_rgba(0,59,27,.045)]"><div className="flex items-start justify-between"><p className="max-w-[70%] text-[10px] font-bold uppercase leading-5 tracking-[.12em] text-ink-variant">{metric.label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-green/8 text-green"><i className="ri-pulse-line" /></span></div><div className="mt-5 flex items-end gap-2"><strong className="font-display text-4xl text-green-deep">{metric.value.toLocaleString('fr-CA')}</strong><span className="pb-1 text-xs text-ink-variant">{metric.unit}</span></div>{metric.changePercent != null && <p className={`mt-2 text-xs font-bold ${metric.changePercent >= 0 ? 'text-green' : 'text-error'}`}>{metric.changePercent >= 0 ? '↑' : '↓'} {Math.abs(metric.changePercent)}% sur 30 jours</p>}</article>)}</section>
    <section className="rounded-[24px] border border-line bg-surface p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-red-link">Six derniers mois</p><h2 className="mt-1 font-display text-2xl font-bold text-green-deep">Activité communautaire</h2></div><p className="text-xs text-ink-variant">Membres · événements · services · occasions</p></div><div className="mt-8 grid grid-cols-6 gap-3">{data.periods.map((period) => <div key={period.period} className="flex min-w-0 flex-col items-center"><div className="flex h-56 w-full items-end justify-center gap-1 border-b border-line px-1">{[period.newMembers, period.eventRegistrations, period.serviceRequests, period.opportunityApplications].map((value, index) => <div key={index} title={`${value}`} className={`w-1/5 min-w-1 rounded-t ${colors[index]}`} style={{ height: `${Math.max(value ? 5 : 0, value / max * 100)}%` }} />)}</div><span className="mt-2 text-[9px] font-bold text-ink-variant">{period.period.slice(5)}</span></div>)}</div><div className="mt-5 flex flex-wrap gap-4 text-xs">{['Nouveaux membres', 'Inscriptions événements', 'Demandes de service', 'Candidatures'].map((label, index) => <span key={label} className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${colors[index]}`} />{label}</span>)}</div></section></>}
  </div>;
}
